package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"slices"
	"time"

	"charm.land/log/v2"
	"github.com/charmbracelet/colorprofile"
	"github.com/charmbracelet/x/term"
	"github.com/nxadm/tail"
	"github.com/rave-soft/sennit/internal/config"
	"github.com/spf13/cobra"
)

const defaultTailLines = 1000

var logsCmd = &cobra.Command{
	Use:   "logs",
	Short: "View sennit logs",
	Long:  `View the logs generated by Sennit. This command allows you to see the log output for debugging and monitoring.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		follow, err := cmd.Flags().GetBool("follow")
		if err != nil {
			return fmt.Errorf("failed to get follow flag: %w", err)
		}

		tailLines, err := cmd.Flags().GetInt("tail")
		if err != nil {
			return fmt.Errorf("failed to get tail flag: %w", err)
		}

		log.SetLevel(log.DebugLevel)
		log.SetOutput(os.Stdout)
		if !term.IsTerminal(os.Stdout.Fd()) {
			log.SetColorProfile(colorprofile.NoTTY)
		}

		if _, _, err := initConfig(cmd, false); err != nil {
			return fmt.Errorf("failed to load configuration: %w", err)
		}
		// The newest log in the directory, not this process's own: logs
		// are per process now (see config.GlobalLogFile), and `sennit
		// logs` is always a process of its own asking about somebody
		// else's - usually the sennit running in the next terminal.
		logsFile := config.LatestGlobalLogFile()
		_, err = os.Stat(logsFile)
		if os.IsNotExist(err) {
			log.Warn("No logs found yet; a log file is created on first run.")
			return nil
		}
		log.Info("Reading logs", "file", logsFile)

		if follow {
			return followLogs(cmd.Context(), logsFile, tailLines)
		}

		return showLogs(logsFile, tailLines)
	},
}

func init() {
	logsCmd.Flags().BoolP("follow", "f", false, "Follow log output")
	logsCmd.Flags().IntP("tail", "t", defaultTailLines, "Show only the last N lines default: 1000 for performance")
}

func followLogs(ctx context.Context, logsFile string, tailLines int) error {
	t, err := tail.TailFile(logsFile, tail.Config{
		Follow: false,
		ReOpen: false,
		Logger: tail.DiscardingLogger,
	})
	if err != nil {
		return fmt.Errorf("failed to tail log file: %w", err)
	}

	lines := drainTailLines(t, tailLines)
	_ = t.Stop() // tail file already drained; process may have exited

	for _, line := range lines {
		printLogLine(line)
	}

	if len(lines) == tailLines {
		fmt.Fprintf(os.Stderr, "\nShowing last %d lines. Full logs available at: %s\n", tailLines, logsFile)
		fmt.Fprintf(os.Stderr, "Following new log entries...\n\n")
	}

	t, err = tail.TailFile(logsFile, tail.Config{
		Follow:   true,
		ReOpen:   true,
		Logger:   tail.DiscardingLogger,
		Location: &tail.SeekInfo{Offset: 0, Whence: io.SeekEnd},
	})
	if err != nil {
		return fmt.Errorf("failed to tail log file: %w", err)
	}
	defer func() { _ = t.Stop() }() // best-effort stop during shutdown

	return runFollowLoop(ctx, t)
}

// runFollowLoop prints new log lines as t.Lines delivers them, until ctx is
// cancelled or the tail dies.
func runFollowLoop(ctx context.Context, t *tail.Tail) error {
	for {
		select {
		case line, ok := <-t.Lines:
			if !ok {
				// nxadm/tail closes t.Lines on an internal error (unlike
				// drainTailLines, which only ranges until the channel
				// empties after a non-follow tail finishes); a receive
				// after that yields a nil line, and line.Err would panic.
				return t.Err()
			}
			if line.Err != nil {
				continue
			}
			printLogLine(line.Text)
		case <-ctx.Done():
			return nil
		}
	}
}

func showLogs(logsFile string, tailLines int) error {
	t, err := tail.TailFile(logsFile, tail.Config{
		Follow:      false,
		ReOpen:      false,
		Logger:      tail.DiscardingLogger,
		MaxLineSize: 0,
	})
	if err != nil {
		return fmt.Errorf("failed to tail log file: %w", err)
	}
	defer func() { _ = t.Stop() }() // best-effort stop during shutdown

	lines := drainTailLines(t, tailLines)

	for _, line := range lines {
		printLogLine(line)
	}

	if len(lines) == tailLines {
		fmt.Fprintf(os.Stderr, "\nShowing last %d lines. Full logs available at: %s\n", tailLines, logsFile)
	}

	return nil
}

// drainTailLines reads every line already queued on t.Lines — the channel
// closes once a non-following tail's initial pass finishes — keeping only
// the last tailLines of them, the way `tail -n` would. Both the one-shot
// "sennit logs" read and the initial catch-up before "sennit logs -f"
// starts following need exactly this.
func drainTailLines(t *tail.Tail, tailLines int) []string {
	var lines []string
	for line := range t.Lines {
		if line.Err != nil {
			continue
		}
		lines = append(lines, line.Text)
		if len(lines) > tailLines {
			lines = lines[len(lines)-tailLines:]
		}
	}
	return lines
}

func printLogLine(lineText string) {
	var data map[string]any
	if err := json.Unmarshal([]byte(lineText), &data); err != nil {
		return
	}
	msg := data["msg"]
	level := data["level"]
	var otherData []any
	var keys []string
	for k := range data {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	for _, k := range keys {
		switch k {
		case "msg", "level", "time":
			continue
		case "source":
			source, ok := data[k].(map[string]any)
			if !ok {
				continue
			}
			// Both fields are checked rather than asserted: this parses
			// whatever is in the log file, and one line written by
			// something else (or truncated mid-write) used to panic the
			// whole command on the bare assertion.
			line, _ := source["line"].(float64)
			sourceFile := fmt.Sprintf("%s:%d", source["file"], int(line))
			otherData = append(otherData, "source", sourceFile)

		default:
			otherData = append(otherData, k, data[k])
		}
	}
	log.SetTimeFunction(func(_ time.Time) time.Time {
		// parse the timestamp from the log line if available
		stamp, ok := data["time"].(string)
		if !ok {
			return time.Now()
		}
		t, err := time.Parse(time.RFC3339, stamp)
		if err != nil {
			return time.Now() // fallback to current time if parsing fails
		}
		return t
	})
	switch level {
	case "INFO":
		log.Info(msg, otherData...)
	case "DEBUG":
		log.Debug(msg, otherData...)
	case "ERROR":
		log.Error(msg, otherData...)
	case "WARN":
		log.Warn(msg, otherData...)
	default:
		log.Info(msg, otherData...)
	}
}
