// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
)

const countFilesForSessionIDs = `-- name: CountFilesForSessionIDs :one
WITH input AS (
    SELECT CAST(?1 AS TEXT) AS session_ids_json
)
SELECT COUNT(*) FROM files
WHERE files.session_id IN (
    SELECT value FROM input, json_each(CAST(input.session_ids_json AS TEXT))
)
`

// gc's dependent-row count for a batch of sessions it is about to delete;
// see CountMessagesForSessionIDs for why json_each replaces an IN-list.
func (q *Queries) CountFilesForSessionIDs(ctx context.Context, sessionIdsJson string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFilesForSessionIDs, sessionIdsJson)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    id,
    session_id,
    path,
    content,
    version,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, path, content, version, created_at, updated_at
`

type CreateFileParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.SessionID,
		arg.Path,
		arg.Content,
		arg.Version,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Path,
		&i.Content,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionFiles = `-- name: DeleteSessionFiles :exec
DELETE FROM files
WHERE session_id = ?
`

func (q *Queries) DeleteSessionFiles(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionFiles, sessionID)
	return err
}

const getFileByPathAndSession = `-- name: GetFileByPathAndSession :one
SELECT id, session_id, path, content, version, created_at, updated_at
FROM files
WHERE path = ? AND session_id = ?
ORDER BY version DESC, created_at DESC
LIMIT 1
`

type GetFileByPathAndSessionParams struct {
	Path      string `json:"path"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByPathAndSession, arg.Path, arg.SessionID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Path,
		&i.Content,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesBySessionTree = `-- name: ListFilesBySessionTree :many
WITH RECURSIVE
ancestors(id, parent_session_id) AS (
    SELECT sessions.id, sessions.parent_session_id
    FROM sessions
    WHERE sessions.id = ?1
    UNION ALL
    SELECT s.id, s.parent_session_id
    FROM sessions s
    JOIN ancestors a ON s.id = a.parent_session_id
),
root(id) AS (
    SELECT ancestors.id
    FROM ancestors
    WHERE ancestors.parent_session_id IS NULL
    LIMIT 1
),
session_tree(id) AS (
    SELECT root.id FROM root
    UNION ALL
    SELECT s.id
    FROM sessions s
    JOIN session_tree tree ON s.parent_session_id = tree.id
)
SELECT files.id, files.session_id, files.path, files.content, files.version, files.created_at, files.updated_at
FROM files
JOIN session_tree ON files.session_id = session_tree.id
ORDER BY files.version ASC, files.created_at ASC
`

func (q *Queries) ListFilesBySessionTree(ctx context.Context, sessionID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFilesBySessionTree, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Path,
			&i.Content,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextFileVersion = `-- name: NextFileVersion :one
SELECT COALESCE(MAX(version), -1) + 1 AS next_version
FROM files
WHERE path = ?
`

// Version numbers are allocated per path across every session, which is
// what makes ListFilesBySessionTree's cross-session ordering and the
// UI's first-to-latest diff meaningful. UNIQUE(path, version) is the key
// that holds this up, so callers must allocate inside the same
// transaction as the insert.
func (q *Queries) NextFileVersion(ctx context.Context, path string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextFileVersion, path)
	var next_version int64
	err := row.Scan(&next_version)
	return next_version, err
}
