// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: latency.sql

package db

import (
	"context"
)

const listAllLatencyEventsSince = `-- name: ListAllLatencyEventsSince :many
SELECT
    kind,
    waited_ms
FROM latency_events
WHERE created_at >= ?
ORDER BY created_at ASC
`

type ListAllLatencyEventsSinceRow struct {
	Kind     string `json:"kind"`
	WaitedMs int64  `json:"waited_ms"`
}

func (q *Queries) ListAllLatencyEventsSince(ctx context.Context, createdAt int64) ([]ListAllLatencyEventsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllLatencyEventsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllLatencyEventsSinceRow{}
	for rows.Next() {
		var i ListAllLatencyEventsSinceRow
		if err := rows.Scan(&i.Kind, &i.WaitedMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatencyEventsSince = `-- name: ListLatencyEventsSince :many
SELECT
    latency_events.kind,
    latency_events.waited_ms
FROM latency_events
JOIN sessions ON sessions.id = latency_events.session_id
WHERE latency_events.created_at >= ?
  AND sessions.project_path = ?
ORDER BY latency_events.created_at ASC
`

type ListLatencyEventsSinceParams struct {
	CreatedAt   int64  `json:"created_at"`
	ProjectPath string `json:"project_path"`
}

type ListLatencyEventsSinceRow struct {
	Kind     string `json:"kind"`
	WaitedMs int64  `json:"waited_ms"`
}

// Scoped by joining sessions rather than by a project_path column of its
// own: the scope of a latency event is the scope of the session that
// produced it, and duplicating the path would let the two disagree after
// a session moves.
func (q *Queries) ListLatencyEventsSince(ctx context.Context, arg ListLatencyEventsSinceParams) ([]ListLatencyEventsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatencyEventsSince, arg.CreatedAt, arg.ProjectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatencyEventsSinceRow{}
	for rows.Next() {
		var i ListLatencyEventsSinceRow
		if err := rows.Scan(&i.Kind, &i.WaitedMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLatencyEvent = `-- name: RecordLatencyEvent :exec

INSERT INTO latency_events (
    session_id,
    kind,
    waited_ms,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    strftime('%s', 'now')
)
`

type RecordLatencyEventParams struct {
	SessionID string `json:"session_id"`
	Kind      string `json:"kind"`
	WaitedMs  int64  `json:"waited_ms"`
}

// The queries below back `sennit stat --by latency`, the per-kind
// breakdown of how long two internal handoffs waited before reaching the
// model. Like stats.sql they return raw rows for a time window rather
// than pre-aggregating: percentiles are computed Go-side over the whole
// distribution (see internal/stats.ComputeLatency), and SQLite has no
// percentile aggregate to lean on anyway.
func (q *Queries) RecordLatencyEvent(ctx context.Context, arg RecordLatencyEventParams) error {
	_, err := q.db.ExecContext(ctx, recordLatencyEvent, arg.SessionID, arg.Kind, arg.WaitedMs)
	return err
}
