// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const batchValidateSessionIDsInTree = `-- name: BatchValidateSessionIDsInTree :many
WITH RECURSIVE
input AS (
    SELECT CAST(?1 AS TEXT) AS session_ids_json
),
tree AS (
    SELECT sessions.id AS session_id
    FROM sessions
    WHERE sessions.id = CAST(?2 AS TEXT)
      AND sessions.project_path = CAST(?3 AS TEXT)
    UNION ALL
    SELECT sessions.id
    FROM sessions
    JOIN tree ON sessions.parent_session_id = tree.session_id
    WHERE sessions.project_path = CAST(?3 AS TEXT)
)
SELECT tree.session_id AS id
FROM tree
WHERE tree.session_id IN (
    SELECT value FROM input, json_each(CAST(input.session_ids_json AS TEXT))
)
`

type BatchValidateSessionIDsInTreeParams struct {
	SessionIdsJson string `json:"session_ids_json"`
	RootSessionID  string `json:"root_session_id"`
	ProjectPath    string `json:"project_path"`
}

func (q *Queries) BatchValidateSessionIDsInTree(ctx context.Context, arg BatchValidateSessionIDsInTreeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, batchValidateSessionIDsInTree, arg.SessionIdsJson, arg.RootSessionID, arg.ProjectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMessagesForSessionIDs = `-- name: CountMessagesForSessionIDs :one
WITH input AS (
    SELECT CAST(?1 AS TEXT) AS session_ids_json
)
SELECT COUNT(*) FROM messages
WHERE messages.session_id IN (
    SELECT value FROM input, json_each(CAST(input.session_ids_json AS TEXT))
)
`

// gc's dependent-row count for a batch of sessions it is about to delete.
// One aggregate query via json_each rather than an IN-list, so the bound
// parameter count does not grow with the number of sessions selected --
// see ListMessagesBySessionIDs for the same pattern.
func (q *Queries) CountMessagesForSessionIDs(ctx context.Context, sessionIdsJson string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesForSessionIDs, sessionIdsJson)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionMessages = `-- name: CountSessionMessages :one
SELECT COUNT(*) FROM messages
WHERE session_id = ?
`

func (q *Queries) CountSessionMessages(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionMessages, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    session_id,
    role,
    parts,
    model,
    provider,
    is_summary_message,
    origin,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, origin, summary_before_tokens, summary_after_tokens
`

type CreateMessageParams struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
	Origin           string         `json:"origin"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.Model,
		arg.Provider,
		arg.IsSummaryMessage,
		arg.Origin,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Origin,
		&i.SummaryBeforeTokens,
		&i.SummaryAfterTokens,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM messages
WHERE session_id = ?
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionMessages, sessionID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, origin, summary_before_tokens, summary_after_tokens
FROM messages
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.Provider,
		&i.IsSummaryMessage,
		&i.Origin,
		&i.SummaryBeforeTokens,
		&i.SummaryAfterTokens,
	)
	return i, err
}

const lastMessageActivity = `-- name: LastMessageActivity :one
SELECT CAST(COALESCE(MAX(updated_at), 0) AS INTEGER) AS last_activity
FROM messages
WHERE session_id = ?
`

// The most recent write to any message in the session, as a Unix
// timestamp. Every streaming delta the assistant produces updates its
// message row (debounced by tens of milliseconds, see
// internal/message/store), so this is the cheapest honest "is this session
// still producing anything" signal there is - and the one the delegation
// idle watchdog reads. Covered by
// idx_messages_session_id. Zero means "no messages at all", which the
// caller reads as "no activity recorded" rather than "the epoch".
func (q *Queries) LastMessageActivity(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastMessageActivity, sessionID)
	var last_activity int64
	err := row.Scan(&last_activity)
	return last_activity, err
}

const listAllUserMessages = `-- name: ListAllUserMessages :many
SELECT messages.id, messages.session_id, messages.role, messages.parts, messages.model, messages.created_at, messages.updated_at, messages.finished_at, messages.provider, messages.is_summary_message, messages.origin, messages.summary_before_tokens, messages.summary_after_tokens
FROM messages
JOIN sessions ON sessions.id = messages.session_id
WHERE messages.role = 'user'
  AND messages.origin = 'person'
  AND sessions.parent_session_id IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM threads
      WHERE threads.session_id = sessions.id
  )
ORDER BY messages.created_at DESC
`

// Prompt-history source: only messages a human typed. Sub-agent child sessions
// and thread sessions carry machine-generated prompts as user-role messages.
func (q *Queries) ListAllUserMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listAllUserMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Origin,
			&i.SummaryBeforeTokens,
			&i.SummaryAfterTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, origin, summary_before_tokens, summary_after_tokens
FROM messages
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Origin,
			&i.SummaryBeforeTokens,
			&i.SummaryAfterTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionIDs = `-- name: ListMessagesBySessionIDs :many
WITH input AS (
    SELECT CAST(?1 AS TEXT) AS session_ids_json
)
SELECT messages.id, messages.session_id, messages.role, messages.parts, messages.model, messages.created_at, messages.updated_at, messages.finished_at, messages.provider, messages.is_summary_message, messages.origin, messages.summary_before_tokens, messages.summary_after_tokens
FROM messages
WHERE messages.session_id IN (
    SELECT value FROM input, json_each(CAST(input.session_ids_json AS TEXT))
)
ORDER BY messages.session_id, messages.created_at ASC
`

func (q *Queries) ListMessagesBySessionIDs(ctx context.Context, sessionIdsJson string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySessionIDs, sessionIdsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Origin,
			&i.SummaryBeforeTokens,
			&i.SummaryAfterTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnfinishedAssistantMessages = `-- name: ListUnfinishedAssistantMessages :many
SELECT m.id, m.session_id, m.role, m.parts, m.model, m.provider,
       m.created_at, m.updated_at, m.finished_at
FROM messages m
JOIN sessions s ON s.id = m.session_id
WHERE s.project_path = ?
  AND m.role = 'assistant'
  AND m.finished_at IS NULL
ORDER BY m.created_at ASC, m.id ASC
`

type ListUnfinishedAssistantMessagesRow struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	Provider   sql.NullString `json:"provider"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

// Assistant messages in a project that carry no Finish part, which is
// what finished_at records (see message.service.write). Every path that
// ends a turn -- normal completion, error, cancel -- writes one, and every
// such path runs inside the process that owns the turn. So a row left
// here belongs to a turn that was killed, and is the starting point for
// closing it out on the next start.
//
// Ordered oldest first so a repair walks a session's history in the
// order it happened.
func (q *Queries) ListUnfinishedAssistantMessages(ctx context.Context, projectPath string) ([]ListUnfinishedAssistantMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnfinishedAssistantMessages, projectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnfinishedAssistantMessagesRow{}
	for rows.Next() {
		var i ListUnfinishedAssistantMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMessagesBySession = `-- name: ListUserMessagesBySession :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message, origin, summary_before_tokens, summary_after_tokens
FROM messages
WHERE session_id = ? AND role = 'user' AND origin = 'person'
ORDER BY created_at DESC
`

func (q *Queries) ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listUserMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
			&i.Origin,
			&i.SummaryBeforeTokens,
			&i.SummaryAfterTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    parts = ?,
    finished_at = ?,
    summary_before_tokens = ?,
    summary_after_tokens = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageParams struct {
	Parts               string        `json:"parts"`
	FinishedAt          sql.NullInt64 `json:"finished_at"`
	SummaryBeforeTokens int64         `json:"summary_before_tokens"`
	SummaryAfterTokens  int64         `json:"summary_after_tokens"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateMessage,
		arg.Parts,
		arg.FinishedAt,
		arg.SummaryBeforeTokens,
		arg.SummaryAfterTokens,
		arg.ID,
	)
	return err
}
