// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type LatencyEvent struct {
	SessionID string `json:"session_id"`
	Kind      string `json:"kind"`
	WaitedMs  int64  `json:"waited_ms"`
	CreatedAt int64  `json:"created_at"`
}

type Message struct {
	ID                  string         `json:"id"`
	SessionID           string         `json:"session_id"`
	Role                string         `json:"role"`
	Parts               string         `json:"parts"`
	Model               sql.NullString `json:"model"`
	CreatedAt           int64          `json:"created_at"`
	UpdatedAt           int64          `json:"updated_at"`
	FinishedAt          sql.NullInt64  `json:"finished_at"`
	Provider            sql.NullString `json:"provider"`
	IsSummaryMessage    int64          `json:"is_summary_message"`
	Origin              string         `json:"origin"`
	SummaryBeforeTokens int64          `json:"summary_before_tokens"`
	SummaryAfterTokens  int64          `json:"summary_after_tokens"`
}

type ReadFile struct {
	SessionID  string `json:"session_id"`
	Path       string `json:"path"`
	ReadAt     int64  `json:"read_at"`
	ReadRanges string `json:"read_ranges"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
	ProjectPath      string         `json:"project_path"`
	AgentID          string         `json:"agent_id"`
	ModelProvider    string         `json:"model_provider"`
	ModelID          string         `json:"model_id"`
}

type SessionWorktreeOwnership struct {
	SessionID          string `json:"session_id"`
	OwnerID            string `json:"owner_id"`
	OwnerRoot          string `json:"owner_root"`
	WorktreeName       string `json:"worktree_name"`
	WorktreePath       string `json:"worktree_path"`
	Phase              string `json:"phase"`
	TargetOwnerID      string `json:"target_owner_id"`
	TargetRoot         string `json:"target_root"`
	TargetWorktreeName string `json:"target_worktree_name"`
	TargetWorktreePath string `json:"target_worktree_path"`
	Epoch              int64  `json:"epoch"`
	UpdatedAt          int64  `json:"updated_at"`
}

type TaskCompletionOutbox struct {
	TaskID          string        `json:"task_id"`
	TerminalAt      int64         `json:"terminal_at"`
	Status          string        `json:"status"`
	Name            string        `json:"name"`
	Goal            string        `json:"goal"`
	SessionID       string        `json:"session_id"`
	ParentSessionID string        `json:"parent_session_id"`
	Error           string        `json:"error"`
	ResultSummary   string        `json:"result_summary"`
	CompletionDepth int64         `json:"completion_depth"`
	CompletedAt     sql.NullInt64 `json:"completed_at"`
}

type Thread struct {
	ID                string        `json:"id"`
	Name              string        `json:"name"`
	ProjectPath       string        `json:"project_path"`
	Goal              string        `json:"goal"`
	BaseBranch        string        `json:"base_branch"`
	Branch            string        `json:"branch"`
	WorktreePath      string        `json:"worktree_path"`
	SessionID         string        `json:"session_id"`
	Status            string        `json:"status"`
	ResultSummary     string        `json:"result_summary"`
	Error             string        `json:"error"`
	CreatedAt         int64         `json:"created_at"`
	UpdatedAt         int64         `json:"updated_at"`
	CompletedAt       sql.NullInt64 `json:"completed_at"`
	Kind              string        `json:"kind"`
	ParentSessionID   string        `json:"parent_session_id"`
	CompletionPending int64         `json:"completion_pending"`
	CompletionDepth   int64         `json:"completion_depth"`
	TerminalAt        sql.NullInt64 `json:"terminal_at"`
	CostAttributed    int64         `json:"cost_attributed"`
	Execution         string        `json:"execution"`
}
