// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	BatchValidateSessionIDsInTree(ctx context.Context, arg BatchValidateSessionIDsInTreeParams) ([]string, error)
	CountSessionFiles(ctx context.Context, sessionID string) (int64, error)
	CountSessionMessages(ctx context.Context, sessionID string) (int64, error)
	CountSessionReadFiles(ctx context.Context, sessionID string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// project_path is denormalized: once session_id is set, the project is
	// also derivable through sessions.project_path. It is stored anyway
	// because a thread exists (and has to be listed and looked up by name)
	// before it has a session at all. The two are kept from diverging by
	// construction (threadspawn.NewStore and session.NewService are both
	// handed the same workspace project path) and by
	// clear_thread_session_refs_on_session_delete, which drops the reference
	// rather than letting it point at a deleted session's project.
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteSessionReadFiles(ctx context.Context, sessionID string) error
	DeleteThread(ctx context.Context, id string) error
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	GetLastSession(ctx context.Context, projectPath string) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	// Unfiltered by kind: entries are addressed by primary key, and callers
	// that hold an id already know what they asked for (id-or-name resolution,
	// RunComplete matching). A kind-scoped caller uses GetThreadByName or
	// ListThreads instead.
	GetThread(ctx context.Context, id string) (Thread, error)
	GetThreadByName(ctx context.Context, arg GetThreadByNameParams) (Thread, error)
	ListAllAssistantMessagesSince(ctx context.Context, createdAt int64) ([]ListAllAssistantMessagesSinceRow, error)
	ListAllDelegationOutcomesSince(ctx context.Context, createdAt int64) ([]ListAllDelegationOutcomesSinceRow, error)
	ListAllLatencyEventsSince(ctx context.Context, createdAt int64) ([]ListAllLatencyEventsSinceRow, error)
	ListAllSessionsSince(ctx context.Context, createdAt int64) ([]ListAllSessionsSinceRow, error)
	// Prompt-history source: only messages a human typed. Sub-agent child sessions
	// and thread sessions carry machine-generated prompts as user-role messages.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	ListAssistantMessagesSince(ctx context.Context, arg ListAssistantMessagesSinceParams) ([]ListAssistantMessagesSinceRow, error)
	// Reports how each background delegation (a task or a thread) ended,
	// joined to the session that ran it so the outcome can be attributed to
	// an agent. Status is the delegation's own terminal state --
	// completed/merged versus failed/cancelled -- which is as close to "did
	// this work land" as the database gets: whether a reviewer approved the
	// change is not something this process records.
	ListDelegationOutcomesSince(ctx context.Context, arg ListDelegationOutcomesSinceParams) ([]ListDelegationOutcomesSinceRow, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListFilesBySessionTree(ctx context.Context, sessionID string) ([]File, error)
	// Scoped by joining sessions rather than by a project_path column of its
	// own: the scope of a latency event is the scope of the session that
	// produced it, and duplicating the path would let the two disagree after
	// a session moves.
	ListLatencyEventsSince(ctx context.Context, arg ListLatencyEventsSinceParams) ([]ListLatencyEventsSinceRow, error)
	// The latest version of each path *within this session*. The maximum has
	// to be taken over the session's own rows: versions are numbered per
	// path across all sessions, so a global MAX(version) matches a sibling
	// session's newer row and this session's files drop out of the result
	// entirely.
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesBySessionIDs(ctx context.Context, sessionIdsJson string) ([]Message, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessionTreeAssistantMessages(ctx context.Context, id string) ([]ListSessionTreeAssistantMessagesRow, error)
	// A session and every descendant of it (agent-tool sub-sessions, title
	// sessions, and their own children), which is the unit a delete has to
	// operate on: parent_session_id carries no foreign key, so nothing
	// cascades from a parent to its children on its own.
	ListSessionTreeIDs(ctx context.Context, sessionID string) ([]string, error)
	// The queries below extend the raw-rows-for-a-window shape above to the
	// two scopes `sennit stat` never needed but the TUI's /stats screen does:
	// one session's own tree, and every project at once. They deliberately
	// return the same columns as their project-scoped counterparts so the
	// Go-side aggregation (internal/stats) can treat all three identically.
	ListSessionTreeSince(ctx context.Context, id string) ([]ListSessionTreeSinceRow, error)
	ListSessions(ctx context.Context, projectPath string) ([]Session, error)
	// Every session across every project, trimmed to the columns `sennit gc`
	// needs to compute its retention set (age filter + parent/child
	// expansion) without pulling message/file bodies into memory. Unscoped by
	// project_path; the caller filters by project in Go for --project.
	ListSessionsForGC(ctx context.Context) ([]ListSessionsForGCRow, error)
	// The queries below back `sennit stat`, a terminal-table
	// breakdown by model/agent/project/skill. They intentionally return raw
	// rows for a time window rather than pre-aggregating, since the
	// model/agent grouping requires Go-side logic (proportional token
	// attribution for multi-model sessions, see internal/cmd/stat.go).
	ListSessionsSince(ctx context.Context, arg ListSessionsSinceParams) ([]ListSessionsSinceRow, error)
	ListSessionsSinceWithAgent(ctx context.Context, arg ListSessionsSinceWithAgentParams) ([]ListSessionsSinceWithAgentRow, error)
	// Counts skill loads by matching the `view` tool's result metadata. Both
	// JSON layers are guarded with json_valid before being extracted: a
	// message part whose parts blob or whose metadata field is not valid JSON
	// (a tool that records a plain string there, say) would otherwise abort
	// the whole query with "malformed JSON", losing every other skill load
	// along with it. Substituting an empty object makes such a row contribute
	// nothing instead of taking the report down.
	ListSkillLoadsSince(ctx context.Context, arg ListSkillLoadsSinceParams) ([]ListSkillLoadsSinceRow, error)
	// The sessions a named sub-agent has already had under one parent, oldest
	// first: every prior turn of the same continuing conversation. agent_id is
	// empty for sessions that are not a named delegation, and the caller must
	// never pass '' here - that would sweep up every unrelated child session.
	ListSubAgentSessions(ctx context.Context, arg ListSubAgentSessionsParams) ([]Session, error)
	// Thread-facing: thread_list, the dashboard, and any other caller that
	// means "threads" specifically. Scoped to kind = 'thread' so a caller
	// asking for threads never sees another delegation kind sharing this
	// table. The generic lifecycle recovery sweep must NOT use this query;
	// see ListThreadsAll.
	ListThreads(ctx context.Context, projectPath string) ([]Thread, error)
	// Every delegation kind sharing this table (threads today, tasks once
	// they exist), scoped to project_path but not kind. This is the listing
	// the generic lifecycle recovery sweep uses: recovery must reconcile
	// every kind after a restart, not just threads, or a non-thread row left
	// "running" when the process died would never be caught and would sit
	// displayed as active forever. Not for thread-facing callers; see
	// ListThreads.
	ListThreadsAll(ctx context.Context, projectPath string) ([]Thread, error)
	// Every delegation across every project, trimmed to the columns `sennit
	// gc` needs to pick finished ones older than the retention cutoff.
	// Unscoped by project_path; the caller filters by project in Go for
	// --project.
	//
	// Deliberately unscoped by kind, unlike the display queries above. gc is
	// not a thread-facing caller -- it is the only thing that reclaims rows
	// here, and a task has nothing else that would: it is never merged (so
	// discardMerged cannot reach it) and the task API has no removal of its
	// own. Scoping this to threads meant finished tasks accumulated for the
	// life of the database. A task carries no worktree, so reclaiming one is
	// the row and its retention alone, with nothing left orphaned on disk.
	ListThreadsForGC(ctx context.Context) ([]ListThreadsForGCRow, error)
	// Assistant messages in a project that carry no Finish part, which is
	// what finished_at records (see message.service.write). Every path that
	// ends a turn -- normal completion, error, cancel -- writes one, and every
	// such path runs inside the process that owns the turn. So a row left
	// here belongs to a turn that was killed, and is the starting point for
	// closing it out on the next start.
	//
	// Ordered oldest first so a repair walks a session's history in the
	// order it happened.
	ListUnfinishedAssistantMessages(ctx context.Context, projectPath string) ([]ListUnfinishedAssistantMessagesRow, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	// Version numbers are allocated per path across every session, which is
	// what makes ListFilesBySessionTree's cross-session ordering and the
	// UI's first-to-latest diff meaningful. UNIQUE(path, version) is the key
	// that holds this up, so callers must allocate inside the same
	// transaction as the insert.
	NextFileVersion(ctx context.Context, path string) (int64, error)
	ProjectStatsSince(ctx context.Context, createdAt int64) ([]ProjectStatsSinceRow, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	// The queries below back `sennit stat --by latency`, the per-kind
	// breakdown of how long two internal handoffs waited before reaching the
	// model. Like stats.sql they return raw rows for a time window rather
	// than pre-aggregating: percentiles are computed Go-side over the whole
	// distribution (see internal/stats.ComputeLatency), and SQLite has no
	// percentile aggregate to lean on anyway.
	RecordLatencyEvent(ctx context.Context, arg RecordLatencyEventParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) error
	// Pin the model a session runs on, so restoring it later restores the
	// model it was working with rather than the instance's current selection.
	// Empty strings clear the pin, returning the session to that fallback.
	//
	// Deliberately not RETURNING the row: this is written on every turn, from
	// the dispatch path, and its result is never read back.
	SetSessionModel(ctx context.Context, arg SetSessionModelParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error
	UpdateThreadSession(ctx context.Context, arg UpdateThreadSessionParams) (Thread, error)
	UpdateThreadStatus(ctx context.Context, arg UpdateThreadStatusParams) (Thread, error)
}

var _ Querier = (*Queries)(nil)
