// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Called in the same transaction as FinalizeTask. A failed transaction rolls
	// this increment back, while the running/marker predicates make retries safe.
	AttributeTaskCostOnce(ctx context.Context, arg AttributeTaskCostOnceParams) (int64, error)
	BatchValidateSessionIDsInTree(ctx context.Context, arg BatchValidateSessionIDsInTreeParams) ([]string, error)
	// gc's dependent-row count for a batch of sessions it is about to delete;
	// see CountMessagesForSessionIDs for why json_each replaces an IN-list.
	CountFilesForSessionIDs(ctx context.Context, sessionIdsJson string) (int64, error)
	// gc's dependent-row count for a batch of sessions it is about to delete.
	// One aggregate query via json_each rather than an IN-list, so the bound
	// parameter count does not grow with the number of sessions selected --
	// see ListMessagesBySessionIDs for the same pattern.
	CountMessagesForSessionIDs(ctx context.Context, sessionIdsJson string) (int64, error)
	// gc's dependent-row count for a batch of sessions it is about to delete;
	// see CountMessagesForSessionIDs for why json_each replaces an IN-list.
	CountReadFilesForSessionIDs(ctx context.Context, sessionIdsJson string) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// project_path is denormalized: once session_id is set, the project is
	// also derivable through sessions.project_path. It is stored anyway
	// because a thread exists (and has to be listed and looked up by name)
	// before it has a session at all. The two are kept from diverging by
	// construction (threadspawn.NewStore and session.NewService are both
	// handed the same workspace project path) and by
	// clear_thread_session_refs_on_session_delete, which drops the reference
	// rather than letting it point at a deleted session's project.
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteSessionReadFiles(ctx context.Context, sessionID string) error
	DeleteThread(ctx context.Context, id string) error
	// This follows AttributeTaskCostOnce in one transaction, so terminal state,
	// attribution and the durable completion outbox become visible together.
	FinalizeTask(ctx context.Context, arg FinalizeTaskParams) (Thread, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error)
	// The most recently updated top-level session in a project: same scope as
	// ListSessions (parent_session_id IS NULL), which also excludes every
	// agent-tool sub-session, since those always carry a parent_session_id.
	GetLastSession(ctx context.Context, projectPath string) (Session, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	// Unfiltered by kind: entries are addressed by primary key, and callers
	// that hold an id already know what they asked for (id-or-name resolution,
	// RunComplete matching). A kind-scoped caller uses GetThreadByName or
	// ListThreads instead.
	GetThread(ctx context.Context, id string) (Thread, error)
	GetThreadByName(ctx context.Context, arg GetThreadByNameParams) (Thread, error)
	// The most recent write to any message in the session, as a Unix
	// timestamp. Every streaming delta the assistant produces updates its
	// message row (debounced by tens of milliseconds, see
	// internal/message/store), so this is the cheapest honest "is this session
	// still producing anything" signal there is - and the one the delegation
	// idle watchdog reads. Covered by
	// idx_messages_session_id. Zero means "no messages at all", which the
	// caller reads as "no activity recorded" rather than "the epoch".
	LastMessageActivity(ctx context.Context, sessionID string) (int64, error)
	ListAllAssistantMessagesSince(ctx context.Context, createdAt int64) ([]ListAllAssistantMessagesSinceRow, error)
	ListAllDelegationOutcomesSince(ctx context.Context, createdAt int64) ([]ListAllDelegationOutcomesSinceRow, error)
	ListAllLatencyEventsSince(ctx context.Context, createdAt int64) ([]ListAllLatencyEventsSinceRow, error)
	ListAllSessionsSince(ctx context.Context, createdAt int64) ([]ListAllSessionsSinceRow, error)
	// Prompt-history source: only messages a human typed. Sub-agent child sessions
	// and thread sessions carry machine-generated prompts as user-role messages.
	ListAllUserMessages(ctx context.Context) ([]Message, error)
	// The queries below back `sennit stat`, a terminal-table
	// breakdown by model/agent/project/skill. They intentionally return raw
	// rows for a time window rather than pre-aggregating, since the
	// model/agent grouping requires Go-side logic (proportional token
	// attribution for multi-model sessions, see internal/cmd/stat.go).
	ListAssistantMessagesSince(ctx context.Context, arg ListAssistantMessagesSinceParams) ([]ListAssistantMessagesSinceRow, error)
	// Reports how each background delegation (a task or a thread) ended,
	// joined to the session that ran it so the outcome can be attributed to
	// an agent. Status is the delegation's own terminal state --
	// completed/merged versus failed/cancelled -- which is as close to "did
	// this work land" as the database gets: whether a reviewer approved the
	// change is not something this process records.
	ListDelegationOutcomesSince(ctx context.Context, arg ListDelegationOutcomesSinceParams) ([]ListDelegationOutcomesSinceRow, error)
	ListFilesBySessionTree(ctx context.Context, sessionID string) ([]File, error)
	// Scoped by joining sessions rather than by a project_path column of its
	// own: the scope of a latency event is the scope of the session that
	// produced it, and duplicating the path would let the two disagree after
	// a session moves.
	ListLatencyEventsSince(ctx context.Context, arg ListLatencyEventsSinceParams) ([]ListLatencyEventsSinceRow, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesBySessionIDs(ctx context.Context, sessionIdsJson string) ([]Message, error)
	ListPendingTaskCompletions(ctx context.Context, projectPath string) ([]Thread, error)
	ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error)
	ListSessionTreeAssistantMessages(ctx context.Context, id string) ([]ListSessionTreeAssistantMessagesRow, error)
	// A session and every descendant of it (agent-tool sub-sessions, title
	// sessions, and their own children), which is the unit a delete has to
	// operate on: parent_session_id carries no foreign key, so nothing
	// cascades from a parent to its children on its own.
	ListSessionTreeIDs(ctx context.Context, sessionID string) ([]string, error)
	// The queries below extend the raw-rows-for-a-window shape above to the
	// two scopes `sennit stat` never needed but the TUI's /stats screen does:
	// one session's own tree, and every project at once. They deliberately
	// return the same columns as their project-scoped counterparts so the
	// Go-side aggregation (internal/stats) can treat all three identically.
	ListSessionTreeSince(ctx context.Context, id string) ([]ListSessionTreeSinceRow, error)
	ListSessions(ctx context.Context, projectPath string) ([]Session, error)
	// Every session across every project, trimmed to the columns `sennit gc`
	// needs to compute its retention set (age filter + parent/child
	// expansion) without pulling message/file bodies into memory. Unscoped by
	// project_path; the caller filters by project in Go for --project.
	ListSessionsForGC(ctx context.Context) ([]ListSessionsForGCRow, error)
	ListSessionsSinceWithAgent(ctx context.Context, arg ListSessionsSinceWithAgentParams) ([]ListSessionsSinceWithAgentRow, error)
	// Counts skill loads by matching the `view` tool's result metadata. Both
	// JSON layers are guarded with json_valid before being extracted: a
	// message part whose parts blob or whose metadata field is not valid JSON
	// (a tool that records a plain string there, say) would otherwise abort
	// the whole query with "malformed JSON", losing every other skill load
	// along with it. Substituting an empty object makes such a row contribute
	// nothing instead of taking the report down.
	ListSkillLoadsSince(ctx context.Context, arg ListSkillLoadsSinceParams) ([]ListSkillLoadsSinceRow, error)
	// The sessions a named sub-agent has already had under one parent, oldest
	// first: every prior turn of the same continuing conversation. agent_id is
	// empty for sessions that are not a named delegation, and the caller must
	// never pass '' here - that would sweep up every unrelated child session.
	ListSubAgentSessions(ctx context.Context, arg ListSubAgentSessionsParams) ([]Session, error)
	// Thread-facing: thread_list, the dashboard, and any other caller that
	// means "threads" specifically. Scoped to kind = 'thread' so a caller
	// asking for threads never sees another delegation kind sharing this
	// table. The generic lifecycle recovery sweep must NOT use this query;
	// see ListThreadsAll.
	ListThreads(ctx context.Context, projectPath string) ([]Thread, error)
	// Every delegation kind sharing this table (threads today, tasks once
	// they exist), scoped to project_path but not kind. This is the listing
	// the generic lifecycle recovery sweep uses: recovery must reconcile
	// every kind after a restart, not just threads, or a non-thread row left
	// "running" when the process died would never be caught and would sit
	// displayed as active forever. Not for thread-facing callers; see
	// ListThreads.
	ListThreadsAll(ctx context.Context, projectPath string) ([]Thread, error)
	// Every delegation across every project, trimmed to the columns `sennit
	// gc` needs to pick finished ones older than the retention cutoff.
	// Unscoped by project_path; the caller filters by project in Go for
	// --project.
	//
	// Deliberately unscoped by kind, unlike the display queries above. gc is
	// not a thread-facing caller -- it is the only thing that reclaims rows
	// here, and a task has nothing else that would: it is never merged (so
	// discardMerged cannot reach it) and the task API has no removal of its
	// own. Scoping this to threads meant finished tasks accumulated for the
	// life of the database. A task carries no worktree, so reclaiming one is
	// the row and its retention alone, with nothing left orphaned on disk.
	//
	// kind, worktree_path and branch are selected so gc can report the
	// worktrees it strands: deleting a thread row leaves its worktree on disk
	// with nothing left to find it by, so gc names them before the row goes.
	//
	// session_id and parent_session_id are selected so gc can protect a
	// session a non-terminal thread still owns (or still delivers its
	// completion into): selectSessions must never sweep either one, even
	// when it belongs to an otherwise-old session tree, or a live delegation's
	// writes hit sessions.id after the row is gone.
	ListThreadsForGC(ctx context.Context) ([]ListThreadsForGCRow, error)
	// Assistant messages in a project that carry no Finish part, which is
	// what finished_at records (see message.service.write). Every path that
	// ends a turn -- normal completion, error, cancel -- writes one, and every
	// such path runs inside the process that owns the turn. So a row left
	// here belongs to a turn that was killed, and is the starting point for
	// closing it out on the next start.
	//
	// Ordered oldest first so a repair walks a session's history in the
	// order it happened.
	ListUnfinishedAssistantMessages(ctx context.Context, projectPath string) ([]ListUnfinishedAssistantMessagesRow, error)
	ListUserMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	MarkTaskCompletionDelivered(ctx context.Context, id string) (int64, error)
	// Version numbers are allocated per path across every session, which is
	// what makes ListFilesBySessionTree's cross-session ordering and the
	// UI's first-to-latest diff meaningful. UNIQUE(path, version) is the key
	// that holds this up, so callers must allocate inside the same
	// transaction as the insert.
	NextFileVersion(ctx context.Context, path string) (int64, error)
	// Cost and tokens sum over every session in the window, sub-agents
	// included, since each session records only its own spend. Sessions and
	// time_seconds stay restricted to top-level rows: a delegation is not a
	// session a person started, and its lifetime runs inside its parent's, so
	// counting it in time_seconds would double-count wall-clock already
	// covered by the parent.
	ProjectStatsSince(ctx context.Context, createdAt int64) ([]ProjectStatsSinceRow, error)
	RecordFileRead(ctx context.Context, arg RecordFileReadParams) error
	// The queries below back `sennit stat --by latency`, the per-kind
	// breakdown of how long two internal handoffs waited before reaching the
	// model. Like stats.sql they return raw rows for a time window rather
	// than pre-aggregating: percentiles are computed Go-side over the whole
	// distribution (see internal/stats.ComputeLatency), and SQLite has no
	// percentile aggregate to lean on anyway.
	RecordLatencyEvent(ctx context.Context, arg RecordLatencyEventParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) (int64, error)
	// Pin the model a session runs on, so restoring it later restores the
	// model it was working with rather than the instance's current selection.
	// Empty strings clear the pin, returning the session to that fallback.
	//
	// Deliberately not RETURNING the row: this is written on every turn, from
	// the dispatch path, and its result is never read back.
	SetSessionModel(ctx context.Context, arg SetSessionModelParams) (int64, error)
	// Write only the todo list. The todo tool runs mid-turn, alongside the
	// turn's own usage saves; a full-row write from either side carried a
	// stale copy of what the other had just written.
	SetSessionTodos(ctx context.Context, arg SetSessionTodosParams) (int64, error)
	// The cost of every session nested under a session, at any depth,
	// excluding the root's own row.
	// Cost is written once per session, never rolled up onto a parent, so a
	// tree total is always a sum computed here rather than a stored column.
	SumDescendantSessionCost(ctx context.Context, sessionID string) (float64, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) (int64, error)
	// Same fields as UpdateSession, minus title, and except cost: this
	// accumulates a delta onto the existing value (cost = cost + ?) instead of
	// overwriting it with the caller's whole running total. Used by a writer
	// whose read-to-write window spans an entire provider stream (summarize):
	// writing back a total computed at the start of that window would
	// silently discard a concurrent cost write (e.g. an async
	// title-generation save against this same session) that landed while
	// the stream was still in flight. title is left out for the same reason:
	// the caller's copy was read before that stream started, so writing it
	// back here would overwrite a title async generation (title.go) set in
	// the meantime, permanently, since that generator never runs a second
	// time once a session has user text. No SaveUsage caller renames a
	// session - renaming goes through RenameSession (session/store's
	// Rename). Save also writes title, but has no production caller of its
	// own: it exists for tests that need to fabricate a session row directly,
	// not as a second write path from the UI (that wide, whole-row write is
	// exactly what G3 closed off - see REFACTORING.md).
	UpdateSessionUsage(ctx context.Context, arg UpdateSessionUsageParams) (Session, error)
	UpdateThreadSession(ctx context.Context, arg UpdateThreadSessionParams) (Thread, error)
	UpdateThreadStatus(ctx context.Context, arg UpdateThreadStatusParams) (Thread, error)
}

var _ Querier = (*Queries)(nil)
