// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_files.sql

package db

import (
	"context"
)

const countReadFilesForSessionIDs = `-- name: CountReadFilesForSessionIDs :one
WITH input AS (
    SELECT CAST(?1 AS TEXT) AS session_ids_json
)
SELECT COUNT(*) FROM read_files
WHERE read_files.session_id IN (
    SELECT value FROM input, json_each(CAST(input.session_ids_json AS TEXT))
)
`

// gc's dependent-row count for a batch of sessions it is about to delete;
// see CountMessagesForSessionIDs for why json_each replaces an IN-list.
func (q *Queries) CountReadFilesForSessionIDs(ctx context.Context, sessionIdsJson string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReadFilesForSessionIDs, sessionIdsJson)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSessionReadFiles = `-- name: DeleteSessionReadFiles :exec
DELETE FROM read_files
WHERE session_id = ?
`

func (q *Queries) DeleteSessionReadFiles(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionReadFiles, sessionID)
	return err
}

const getFileRead = `-- name: GetFileRead :one
SELECT session_id, path, read_at, read_ranges FROM read_files
WHERE session_id = ? AND path = ? LIMIT 1
`

type GetFileReadParams struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

func (q *Queries) GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error) {
	row := q.db.QueryRowContext(ctx, getFileRead, arg.SessionID, arg.Path)
	var i ReadFile
	err := row.Scan(
		&i.SessionID,
		&i.Path,
		&i.ReadAt,
		&i.ReadRanges,
	)
	return i, err
}

const listSessionReadFiles = `-- name: ListSessionReadFiles :many
SELECT session_id, path, read_at, read_ranges FROM read_files
WHERE session_id = ?
ORDER BY read_at DESC
`

func (q *Queries) ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error) {
	rows, err := q.db.QueryContext(ctx, listSessionReadFiles, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadFile{}
	for rows.Next() {
		var i ReadFile
		if err := rows.Scan(
			&i.SessionID,
			&i.Path,
			&i.ReadAt,
			&i.ReadRanges,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFileRead = `-- name: RecordFileRead :exec
INSERT INTO read_files (
    session_id,
    path,
    read_at,
    read_ranges
) VALUES (
    ?,
    ?,
    CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER),
    ?
) ON CONFLICT(path, session_id) DO UPDATE SET
    read_at = excluded.read_at,
    read_ranges = excluded.read_ranges
`

type RecordFileReadParams struct {
	SessionID  string `json:"session_id"`
	Path       string `json:"path"`
	ReadRanges string `json:"read_ranges"`
}

func (q *Queries) RecordFileRead(ctx context.Context, arg RecordFileReadParams) error {
	_, err := q.db.ExecContext(ctx, recordFileRead, arg.SessionID, arg.Path, arg.ReadRanges)
	return err
}
