// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary_message_id,
    project_path,
    agent_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, project_path, agent_id, model_provider, model_id
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	ProjectPath      string         `json:"project_path"`
	AgentID          string         `json:"agent_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ProjectPath,
		arg.AgentID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.ProjectPath,
		&i.AgentID,
		&i.ModelProvider,
		&i.ModelID,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getLastSession = `-- name: GetLastSession :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, project_path, agent_id, model_provider, model_id
FROM sessions
WHERE project_path = ? AND parent_session_id IS NULL
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

// The most recently updated top-level session in a project: same scope as
// ListSessions (parent_session_id IS NULL), which also excludes every
// agent-tool sub-session, since those always carry a parent_session_id.
func (q *Queries) GetLastSession(ctx context.Context, projectPath string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getLastSession, projectPath)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.ProjectPath,
		&i.AgentID,
		&i.ModelProvider,
		&i.ModelID,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, project_path, agent_id, model_provider, model_id
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.ProjectPath,
		&i.AgentID,
		&i.ModelProvider,
		&i.ModelID,
	)
	return i, err
}

const listSessionTreeIDs = `-- name: ListSessionTreeIDs :many
WITH RECURSIVE tree(id) AS (
    SELECT sessions.id
    FROM sessions
    WHERE sessions.id = ?1
    UNION
    SELECT sessions.id
    FROM sessions
    JOIN tree ON sessions.parent_session_id = tree.id
)
SELECT tree.id FROM tree
`

// A session and every descendant of it (agent-tool sub-sessions, title
// sessions, and their own children), which is the unit a delete has to
// operate on: parent_session_id carries no foreign key, so nothing
// cascades from a parent to its children on its own.
func (q *Queries) ListSessionTreeIDs(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSessionTreeIDs, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, project_path, agent_id, model_provider, model_id
FROM sessions
WHERE parent_session_id is NULL AND project_path = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, projectPath string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, projectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.ProjectPath,
			&i.AgentID,
			&i.ModelProvider,
			&i.ModelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForGC = `-- name: ListSessionsForGC :many
SELECT id, parent_session_id, project_path, updated_at
FROM sessions
`

type ListSessionsForGCRow struct {
	ID              string         `json:"id"`
	ParentSessionID sql.NullString `json:"parent_session_id"`
	ProjectPath     string         `json:"project_path"`
	UpdatedAt       int64          `json:"updated_at"`
}

// Every session across every project, trimmed to the columns `sennit gc`
// needs to compute its retention set (age filter + parent/child
// expansion) without pulling message/file bodies into memory. Unscoped by
// project_path; the caller filters by project in Go for --project.
func (q *Queries) ListSessionsForGC(ctx context.Context) ([]ListSessionsForGCRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForGC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForGCRow{}
	for rows.Next() {
		var i ListSessionsForGCRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.ProjectPath,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubAgentSessions = `-- name: ListSubAgentSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, project_path, agent_id, model_provider, model_id
FROM sessions
WHERE parent_session_id = ?
  AND agent_id = ?
  AND agent_id != ''
  AND id != ?
ORDER BY created_at ASC, id ASC
`

type ListSubAgentSessionsParams struct {
	ParentSessionID sql.NullString `json:"parent_session_id"`
	AgentID         string         `json:"agent_id"`
	ID              string         `json:"id"`
}

// The sessions a named sub-agent has already had under one parent, oldest
// first: every prior turn of the same continuing conversation. agent_id is
// empty for sessions that are not a named delegation, and the caller must
// never pass ” here - that would sweep up every unrelated child session.
func (q *Queries) ListSubAgentSessions(ctx context.Context, arg ListSubAgentSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSubAgentSessions, arg.ParentSessionID, arg.AgentID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.ProjectPath,
			&i.AgentID,
			&i.ModelProvider,
			&i.ModelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :execrows
UPDATE sessions
SET
    title = ?
WHERE id = ?
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameSession, arg.Title, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSessionModel = `-- name: SetSessionModel :execrows
UPDATE sessions
SET
    model_provider = ?,
    model_id = ?
WHERE id = ?
`

type SetSessionModelParams struct {
	ModelProvider string `json:"model_provider"`
	ModelID       string `json:"model_id"`
	ID            string `json:"id"`
}

// Pin the model a session runs on, so restoring it later restores the
// model it was working with rather than the instance's current selection.
// Empty strings clear the pin, returning the session to that fallback.
//
// Deliberately not RETURNING the row: this is written on every turn, from
// the dispatch path, and its result is never read back.
func (q *Queries) SetSessionModel(ctx context.Context, arg SetSessionModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionModel, arg.ModelProvider, arg.ModelID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSessionTodos = `-- name: SetSessionTodos :execrows
UPDATE sessions
SET
    todos = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type SetSessionTodosParams struct {
	Todos sql.NullString `json:"todos"`
	ID    string         `json:"id"`
}

// Write only the todo list. The todo tool runs mid-turn, alongside the
// turn's own usage saves; a full-row write from either side carried a
// stale copy of what the other had just written.
func (q *Queries) SetSessionTodos(ctx context.Context, arg SetSessionTodosParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionTodos, arg.Todos, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumDescendantSessionCost = `-- name: SumDescendantSessionCost :one
WITH RECURSIVE tree(id) AS (
    SELECT sessions.id
    FROM sessions
    WHERE sessions.id = ?1
    UNION ALL
    SELECT sessions.id
    FROM sessions
    JOIN tree ON sessions.parent_session_id = tree.id
)
SELECT CAST(COALESCE(SUM(sessions.cost), 0) AS REAL) AS cost
FROM sessions
JOIN tree ON tree.id = sessions.id
WHERE sessions.id != ?1
`

// The cost of every session nested under a session, at any depth,
// excluding the root's own row.
// Cost is written once per session, never rolled up onto a parent, so a
// tree total is always a sum computed here rather than a stored column.
func (q *Queries) SumDescendantSessionCost(ctx context.Context, sessionID string) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumDescendantSessionCost, sessionID)
	var cost float64
	err := row.Scan(&cost)
	return cost, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    summary_message_id = ?,
    cost = ?,
    todos = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, project_path, agent_id, model_provider, model_id
`

type UpdateSessionParams struct {
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Cost             float64        `json:"cost"`
	Todos            sql.NullString `json:"todos"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.Todos,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.ProjectPath,
		&i.AgentID,
		&i.ModelProvider,
		&i.ModelID,
	)
	return i, err
}

const updateSessionTitleAndUsage = `-- name: UpdateSessionTitleAndUsage :execrows
UPDATE sessions
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionUsage = `-- name: UpdateSessionUsage :one
UPDATE sessions
SET
    prompt_tokens = ?,
    completion_tokens = ?,
    summary_message_id = ?,
    cost = cost + ?,
    todos = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, project_path, agent_id, model_provider, model_id
`

type UpdateSessionUsageParams struct {
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Cost             float64        `json:"cost"`
	Todos            sql.NullString `json:"todos"`
	ID               string         `json:"id"`
}

// Same fields as UpdateSession, minus title, and except cost: this
// accumulates a delta onto the existing value (cost = cost + ?) instead of
// overwriting it with the caller's whole running total. Used by a writer
// whose read-to-write window spans an entire provider stream (summarize):
// writing back a total computed at the start of that window would
// silently discard a concurrent cost write (e.g. an async
// title-generation save against this same session) that landed while
// the stream was still in flight. title is left out for the same reason:
// the caller's copy was read before that stream started, so writing it
// back here would overwrite a title async generation (title.go) set in
// the meantime, permanently, since that generator never runs a second
// time once a session has user text. No SaveUsage caller renames a
// session - that is Save's and Rename's job.
func (q *Queries) UpdateSessionUsage(ctx context.Context, arg UpdateSessionUsageParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionUsage,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.Todos,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.ProjectPath,
		&i.AgentID,
		&i.ModelProvider,
		&i.ModelID,
	)
	return i, err
}
