// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"database/sql"
)

const listAllAssistantMessagesSince = `-- name: ListAllAssistantMessagesSince :many
SELECT
    messages.session_id,
    COALESCE(messages.model, 'unknown') as model,
    COALESCE(messages.provider, 'unknown') as provider,
    messages.created_at,
    COALESCE(messages.finished_at, messages.created_at) as finished_at
FROM messages
WHERE messages.role = 'assistant'
  AND messages.created_at >= ?
ORDER BY messages.created_at ASC
`

type ListAllAssistantMessagesSinceRow struct {
	SessionID  string `json:"session_id"`
	Model      string `json:"model"`
	Provider   string `json:"provider"`
	CreatedAt  int64  `json:"created_at"`
	FinishedAt int64  `json:"finished_at"`
}

func (q *Queries) ListAllAssistantMessagesSince(ctx context.Context, createdAt int64) ([]ListAllAssistantMessagesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllAssistantMessagesSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllAssistantMessagesSinceRow{}
	for rows.Next() {
		var i ListAllAssistantMessagesSinceRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDelegationOutcomesSince = `-- name: ListAllDelegationOutcomesSince :many
SELECT
    threads.id,
    threads.kind,
    threads.status,
    threads.session_id,
    COALESCE(sessions.agent_id, '') as agent_id,
    COALESCE(sessions.title, '') as title,
    threads.created_at,
    COALESCE(threads.completed_at, threads.updated_at) as completed_at
FROM threads
LEFT JOIN sessions ON sessions.id = threads.session_id
WHERE threads.created_at >= ?
ORDER BY threads.created_at ASC
`

type ListAllDelegationOutcomesSinceRow struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	Status      string `json:"status"`
	SessionID   string `json:"session_id"`
	AgentID     string `json:"agent_id"`
	Title       string `json:"title"`
	CreatedAt   int64  `json:"created_at"`
	CompletedAt int64  `json:"completed_at"`
}

func (q *Queries) ListAllDelegationOutcomesSince(ctx context.Context, createdAt int64) ([]ListAllDelegationOutcomesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDelegationOutcomesSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDelegationOutcomesSinceRow{}
	for rows.Next() {
		var i ListAllDelegationOutcomesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.SessionID,
			&i.AgentID,
			&i.Title,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSessionsSince = `-- name: ListAllSessionsSince :many
SELECT
    id,
    parent_session_id,
    title,
    agent_id,
    prompt_tokens,
    completion_tokens,
    cost,
    created_at,
    updated_at
FROM sessions
WHERE created_at >= ?
ORDER BY created_at ASC
`

type ListAllSessionsSinceRow struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	AgentID          string         `json:"agent_id"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) ListAllSessionsSince(ctx context.Context, createdAt int64) ([]ListAllSessionsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessionsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSessionsSinceRow{}
	for rows.Next() {
		var i ListAllSessionsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.AgentID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantMessagesSince = `-- name: ListAssistantMessagesSince :many
SELECT
    messages.session_id,
    COALESCE(messages.model, 'unknown') as model,
    COALESCE(messages.provider, 'unknown') as provider,
    messages.created_at,
    COALESCE(messages.finished_at, messages.created_at) as finished_at
FROM messages
JOIN sessions ON sessions.id = messages.session_id
WHERE messages.role = 'assistant'
  AND messages.created_at >= ?
  AND sessions.project_path = ?
ORDER BY messages.created_at ASC
`

type ListAssistantMessagesSinceParams struct {
	CreatedAt   int64  `json:"created_at"`
	ProjectPath string `json:"project_path"`
}

type ListAssistantMessagesSinceRow struct {
	SessionID  string `json:"session_id"`
	Model      string `json:"model"`
	Provider   string `json:"provider"`
	CreatedAt  int64  `json:"created_at"`
	FinishedAt int64  `json:"finished_at"`
}

func (q *Queries) ListAssistantMessagesSince(ctx context.Context, arg ListAssistantMessagesSinceParams) ([]ListAssistantMessagesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantMessagesSince, arg.CreatedAt, arg.ProjectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssistantMessagesSinceRow{}
	for rows.Next() {
		var i ListAssistantMessagesSinceRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelegationOutcomesSince = `-- name: ListDelegationOutcomesSince :many
SELECT
    threads.id,
    threads.kind,
    threads.status,
    threads.session_id,
    COALESCE(sessions.agent_id, '') as agent_id,
    COALESCE(sessions.title, '') as title,
    threads.created_at,
    COALESCE(threads.completed_at, threads.updated_at) as completed_at
FROM threads
LEFT JOIN sessions ON sessions.id = threads.session_id
WHERE threads.created_at >= ?
  AND threads.project_path = ?
ORDER BY threads.created_at ASC
`

type ListDelegationOutcomesSinceParams struct {
	CreatedAt   int64  `json:"created_at"`
	ProjectPath string `json:"project_path"`
}

type ListDelegationOutcomesSinceRow struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	Status      string `json:"status"`
	SessionID   string `json:"session_id"`
	AgentID     string `json:"agent_id"`
	Title       string `json:"title"`
	CreatedAt   int64  `json:"created_at"`
	CompletedAt int64  `json:"completed_at"`
}

// Reports how each background delegation (a task or a thread) ended,
// joined to the session that ran it so the outcome can be attributed to
// an agent. Status is the delegation's own terminal state --
// completed/merged versus failed/cancelled -- which is as close to "did
// this work land" as the database gets: whether a reviewer approved the
// change is not something this process records.
func (q *Queries) ListDelegationOutcomesSince(ctx context.Context, arg ListDelegationOutcomesSinceParams) ([]ListDelegationOutcomesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listDelegationOutcomesSince, arg.CreatedAt, arg.ProjectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDelegationOutcomesSinceRow{}
	for rows.Next() {
		var i ListDelegationOutcomesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.SessionID,
			&i.AgentID,
			&i.Title,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTreeAssistantMessages = `-- name: ListSessionTreeAssistantMessages :many
WITH RECURSIVE tree(id) AS (
    SELECT sessions.id FROM sessions WHERE sessions.id = ?
    UNION
    SELECT sessions.id
    FROM sessions
    JOIN tree ON sessions.parent_session_id = tree.id
)
SELECT
    messages.session_id,
    COALESCE(messages.model, 'unknown') as model,
    COALESCE(messages.provider, 'unknown') as provider,
    messages.created_at,
    COALESCE(messages.finished_at, messages.created_at) as finished_at
FROM messages
JOIN tree ON tree.id = messages.session_id
WHERE messages.role = 'assistant'
ORDER BY messages.created_at ASC
`

type ListSessionTreeAssistantMessagesRow struct {
	SessionID  string `json:"session_id"`
	Model      string `json:"model"`
	Provider   string `json:"provider"`
	CreatedAt  int64  `json:"created_at"`
	FinishedAt int64  `json:"finished_at"`
}

func (q *Queries) ListSessionTreeAssistantMessages(ctx context.Context, id string) ([]ListSessionTreeAssistantMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionTreeAssistantMessages, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionTreeAssistantMessagesRow{}
	for rows.Next() {
		var i ListSessionTreeAssistantMessagesRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTreeSince = `-- name: ListSessionTreeSince :many

WITH RECURSIVE tree(id) AS (
    SELECT sessions.id FROM sessions WHERE sessions.id = ?
    UNION
    SELECT sessions.id
    FROM sessions
    JOIN tree ON sessions.parent_session_id = tree.id
)
SELECT
    sessions.id,
    sessions.parent_session_id,
    sessions.title,
    sessions.agent_id,
    sessions.prompt_tokens,
    sessions.completion_tokens,
    sessions.cost,
    sessions.created_at,
    sessions.updated_at
FROM sessions
JOIN tree ON tree.id = sessions.id
ORDER BY sessions.created_at ASC
`

type ListSessionTreeSinceRow struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	AgentID          string         `json:"agent_id"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

// The queries below extend the raw-rows-for-a-window shape above to the
// two scopes `sennit stat` never needed but the TUI's /stats screen does:
// one session's own tree, and every project at once. They deliberately
// return the same columns as their project-scoped counterparts so the
// Go-side aggregation (internal/stats) can treat all three identically.
func (q *Queries) ListSessionTreeSince(ctx context.Context, id string) ([]ListSessionTreeSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionTreeSince, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionTreeSinceRow{}
	for rows.Next() {
		var i ListSessionTreeSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.AgentID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsSince = `-- name: ListSessionsSince :many

SELECT
    id,
    parent_session_id,
    title,
    prompt_tokens,
    completion_tokens,
    cost,
    created_at,
    updated_at
FROM sessions
WHERE created_at >= ?
  AND project_path = ?
ORDER BY created_at ASC
`

type ListSessionsSinceParams struct {
	CreatedAt   int64  `json:"created_at"`
	ProjectPath string `json:"project_path"`
}

type ListSessionsSinceRow struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

// The queries below back `sennit stat`, a terminal-table
// breakdown by model/agent/project/skill. They intentionally return raw
// rows for a time window rather than pre-aggregating, since the
// model/agent grouping requires Go-side logic (proportional token
// attribution for multi-model sessions, see internal/cmd/stat.go).
func (q *Queries) ListSessionsSince(ctx context.Context, arg ListSessionsSinceParams) ([]ListSessionsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsSince, arg.CreatedAt, arg.ProjectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsSinceRow{}
	for rows.Next() {
		var i ListSessionsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsSinceWithAgent = `-- name: ListSessionsSinceWithAgent :many
SELECT
    id,
    parent_session_id,
    title,
    agent_id,
    prompt_tokens,
    completion_tokens,
    cost,
    created_at,
    updated_at
FROM sessions
WHERE created_at >= ?
  AND project_path = ?
ORDER BY created_at ASC
`

type ListSessionsSinceWithAgentParams struct {
	CreatedAt   int64  `json:"created_at"`
	ProjectPath string `json:"project_path"`
}

type ListSessionsSinceWithAgentRow struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	AgentID          string         `json:"agent_id"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) ListSessionsSinceWithAgent(ctx context.Context, arg ListSessionsSinceWithAgentParams) ([]ListSessionsSinceWithAgentRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsSinceWithAgent, arg.CreatedAt, arg.ProjectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsSinceWithAgentRow{}
	for rows.Next() {
		var i ListSessionsSinceWithAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.AgentID,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillLoadsSince = `-- name: ListSkillLoadsSince :many
WITH parts AS (
    SELECT
        messages.session_id AS session_id,
        messages.created_at AS created_at,
        CASE
            WHEN json_valid(json_extract(value, '$.data.metadata'))
            THEN json_extract(value, '$.data.metadata')
            ELSE '{}'
        END AS metadata
    FROM messages
    JOIN sessions ON sessions.id = messages.session_id,
    json_each(CASE WHEN json_valid(messages.parts) THEN messages.parts ELSE '[]' END)
    WHERE messages.role = 'tool'
      AND messages.created_at >= ?
      AND sessions.project_path = ?
      AND json_extract(value, '$.type') = 'tool_result'
)
SELECT
    json_extract(metadata, '$.resource_name') as skill_name,
    COUNT(*) as load_count,
    COUNT(DISTINCT session_id) as session_count,
    MIN(created_at) as first_used_at,
    MAX(created_at) as last_used_at
FROM parts
WHERE json_extract(metadata, '$.resource_type') = 'skill'
  AND json_extract(metadata, '$.resource_name') IS NOT NULL
GROUP BY skill_name
ORDER BY load_count DESC
`

type ListSkillLoadsSinceParams struct {
	CreatedAt   int64  `json:"created_at"`
	ProjectPath string `json:"project_path"`
}

type ListSkillLoadsSinceRow struct {
	SkillName    interface{} `json:"skill_name"`
	LoadCount    int64       `json:"load_count"`
	SessionCount int64       `json:"session_count"`
	FirstUsedAt  interface{} `json:"first_used_at"`
	LastUsedAt   interface{} `json:"last_used_at"`
}

// Counts skill loads by matching the `view` tool's result metadata. Both
// JSON layers are guarded with json_valid before being extracted: a
// message part whose parts blob or whose metadata field is not valid JSON
// (a tool that records a plain string there, say) would otherwise abort
// the whole query with "malformed JSON", losing every other skill load
// along with it. Substituting an empty object makes such a row contribute
// nothing instead of taking the report down.
func (q *Queries) ListSkillLoadsSince(ctx context.Context, arg ListSkillLoadsSinceParams) ([]ListSkillLoadsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkillLoadsSince, arg.CreatedAt, arg.ProjectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillLoadsSinceRow{}
	for rows.Next() {
		var i ListSkillLoadsSinceRow
		if err := rows.Scan(
			&i.SkillName,
			&i.LoadCount,
			&i.SessionCount,
			&i.FirstUsedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectStatsSince = `-- name: ProjectStatsSince :many
SELECT
    project_path,
    COUNT(*) as sessions,
    COALESCE(SUM(prompt_tokens), 0) as prompt_tokens,
    COALESCE(SUM(completion_tokens), 0) as completion_tokens,
    COALESCE(SUM(cost), 0) as cost,
    COALESCE(SUM(updated_at - created_at), 0) as time_seconds
FROM sessions
WHERE created_at >= ? AND parent_session_id IS NULL
GROUP BY project_path
ORDER BY (prompt_tokens + completion_tokens) DESC
`

type ProjectStatsSinceRow struct {
	ProjectPath      string      `json:"project_path"`
	Sessions         int64       `json:"sessions"`
	PromptTokens     interface{} `json:"prompt_tokens"`
	CompletionTokens interface{} `json:"completion_tokens"`
	Cost             interface{} `json:"cost"`
	TimeSeconds      interface{} `json:"time_seconds"`
}

func (q *Queries) ProjectStatsSince(ctx context.Context, createdAt int64) ([]ProjectStatsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, projectStatsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectStatsSinceRow{}
	for rows.Next() {
		var i ProjectStatsSinceRow
		if err := rows.Scan(
			&i.ProjectPath,
			&i.Sessions,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.TimeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
