// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"database/sql"
)

const listAssistantMessagesSince = `-- name: ListAssistantMessagesSince :many
SELECT
    session_id,
    COALESCE(model, 'unknown') as model,
    COALESCE(provider, 'unknown') as provider,
    created_at,
    COALESCE(finished_at, created_at) as finished_at
FROM messages
WHERE role = 'assistant'
  AND created_at >= ?
ORDER BY created_at ASC
`

type ListAssistantMessagesSinceRow struct {
	SessionID  string `json:"session_id"`
	Model      string `json:"model"`
	Provider   string `json:"provider"`
	CreatedAt  int64  `json:"created_at"`
	FinishedAt int64  `json:"finished_at"`
}

func (q *Queries) ListAssistantMessagesSince(ctx context.Context, createdAt int64) ([]ListAssistantMessagesSinceRow, error) {
	rows, err := q.query(ctx, q.listAssistantMessagesSinceStmt, listAssistantMessagesSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssistantMessagesSinceRow{}
	for rows.Next() {
		var i ListAssistantMessagesSinceRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsSince = `-- name: ListSessionsSince :many

SELECT
    id,
    parent_session_id,
    title,
    prompt_tokens,
    completion_tokens,
    cost,
    created_at,
    updated_at
FROM sessions
WHERE created_at >= ?
ORDER BY created_at ASC
`

type ListSessionsSinceRow struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
}

// The queries below back `braid stat`, a terminal-table
// breakdown by model/agent/project/skill. They intentionally return raw
// rows for a time window rather than pre-aggregating, since the
// model/agent grouping requires Go-side logic (proportional token
// attribution for multi-model sessions, see internal/cmd/stat.go).
func (q *Queries) ListSessionsSince(ctx context.Context, createdAt int64) ([]ListSessionsSinceRow, error) {
	rows, err := q.query(ctx, q.listSessionsSinceStmt, listSessionsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsSinceRow{}
	for rows.Next() {
		var i ListSessionsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillLoadsSince = `-- name: ListSkillLoadsSince :many
SELECT
    json_extract(json_extract(value, '$.data.metadata'), '$.resource_name') as skill_name,
    COUNT(*) as load_count,
    COUNT(DISTINCT messages.session_id) as session_count,
    MIN(messages.created_at) as first_used_at,
    MAX(messages.created_at) as last_used_at
FROM messages, json_each(messages.parts)
WHERE messages.role = 'tool'
  AND messages.created_at >= ?
  AND json_extract(value, '$.type') = 'tool_result'
  AND json_extract(json_extract(value, '$.data.metadata'), '$.resource_type') = 'skill'
  AND json_extract(json_extract(value, '$.data.metadata'), '$.resource_name') IS NOT NULL
GROUP BY skill_name
ORDER BY load_count DESC
`

type ListSkillLoadsSinceRow struct {
	SkillName    interface{} `json:"skill_name"`
	LoadCount    int64       `json:"load_count"`
	SessionCount int64       `json:"session_count"`
	FirstUsedAt  interface{} `json:"first_used_at"`
	LastUsedAt   interface{} `json:"last_used_at"`
}

func (q *Queries) ListSkillLoadsSince(ctx context.Context, createdAt int64) ([]ListSkillLoadsSinceRow, error) {
	rows, err := q.query(ctx, q.listSkillLoadsSinceStmt, listSkillLoadsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillLoadsSinceRow{}
	for rows.Next() {
		var i ListSkillLoadsSinceRow
		if err := rows.Scan(
			&i.SkillName,
			&i.LoadCount,
			&i.SessionCount,
			&i.FirstUsedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
