// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: strands.sql

package db

import (
	"context"
	"database/sql"
)

const createStrand = `-- name: CreateStrand :one
INSERT INTO strands (
    id,
    name,
    goal,
    base_branch,
    branch,
    worktree_path,
    session_id,
    status,
    merge_policy,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
`

type CreateStrandParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Goal         string `json:"goal"`
	BaseBranch   string `json:"base_branch"`
	Branch       string `json:"branch"`
	WorktreePath string `json:"worktree_path"`
	SessionID    string `json:"session_id"`
	Status       string `json:"status"`
	MergePolicy  string `json:"merge_policy"`
}

func (q *Queries) CreateStrand(ctx context.Context, arg CreateStrandParams) (Strand, error) {
	row := q.queryRow(ctx, q.createStrandStmt, createStrand,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.BaseBranch,
		arg.Branch,
		arg.WorktreePath,
		arg.SessionID,
		arg.Status,
		arg.MergePolicy,
	)
	var i Strand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteStrand = `-- name: DeleteStrand :exec
DELETE FROM strands
WHERE id = ?
`

func (q *Queries) DeleteStrand(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteStrandStmt, deleteStrand, id)
	return err
}

const getStrand = `-- name: GetStrand :one
SELECT id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
FROM strands
WHERE id = ? LIMIT 1
`

func (q *Queries) GetStrand(ctx context.Context, id string) (Strand, error) {
	row := q.queryRow(ctx, q.getStrandStmt, getStrand, id)
	var i Strand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getStrandByName = `-- name: GetStrandByName :one
SELECT id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
FROM strands
WHERE name = ? LIMIT 1
`

func (q *Queries) GetStrandByName(ctx context.Context, name string) (Strand, error) {
	row := q.queryRow(ctx, q.getStrandByNameStmt, getStrandByName, name)
	var i Strand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listStrands = `-- name: ListStrands :many
SELECT id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
FROM strands
ORDER BY created_at
`

func (q *Queries) ListStrands(ctx context.Context) ([]Strand, error) {
	rows, err := q.query(ctx, q.listStrandsStmt, listStrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Strand{}
	for rows.Next() {
		var i Strand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Goal,
			&i.BaseBranch,
			&i.Branch,
			&i.WorktreePath,
			&i.SessionID,
			&i.Status,
			&i.MergePolicy,
			&i.ResultSummary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStrandSession = `-- name: UpdateStrandSession :one
UPDATE strands
SET
    session_id = ?
WHERE id = ?
RETURNING id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
`

type UpdateStrandSessionParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateStrandSession(ctx context.Context, arg UpdateStrandSessionParams) (Strand, error) {
	row := q.queryRow(ctx, q.updateStrandSessionStmt, updateStrandSession, arg.SessionID, arg.ID)
	var i Strand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateStrandStatus = `-- name: UpdateStrandStatus :one
UPDATE strands
SET
    status = ?,
    error = ?,
    result_summary = ?,
    completed_at = ?
WHERE id = ?
RETURNING id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
`

type UpdateStrandStatusParams struct {
	Status        string        `json:"status"`
	Error         string        `json:"error"`
	ResultSummary string        `json:"result_summary"`
	CompletedAt   sql.NullInt64 `json:"completed_at"`
	ID            string        `json:"id"`
}

func (q *Queries) UpdateStrandStatus(ctx context.Context, arg UpdateStrandStatusParams) (Strand, error) {
	row := q.queryRow(ctx, q.updateStrandStatusStmt, updateStrandStatus,
		arg.Status,
		arg.Error,
		arg.ResultSummary,
		arg.CompletedAt,
		arg.ID,
	)
	var i Strand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
