// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package db

import (
	"context"
	"database/sql"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
    id,
    name,
    goal,
    base_branch,
    branch,
    worktree_path,
    session_id,
    status,
    merge_policy,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
`

type CreateThreadParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Goal         string `json:"goal"`
	BaseBranch   string `json:"base_branch"`
	Branch       string `json:"branch"`
	WorktreePath string `json:"worktree_path"`
	SessionID    string `json:"session_id"`
	Status       string `json:"status"`
	MergePolicy  string `json:"merge_policy"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.queryRow(ctx, q.createThreadStmt, createThread,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.BaseBranch,
		arg.Branch,
		arg.WorktreePath,
		arg.SessionID,
		arg.Status,
		arg.MergePolicy,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads
WHERE id = ?
`

func (q *Queries) DeleteThread(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteThreadStmt, deleteThread, id)
	return err
}

const getThread = `-- name: GetThread :one
SELECT id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
FROM threads
WHERE id = ? LIMIT 1
`

func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.queryRow(ctx, q.getThreadStmt, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getThreadByName = `-- name: GetThreadByName :one
SELECT id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
FROM threads
WHERE name = ? LIMIT 1
`

func (q *Queries) GetThreadByName(ctx context.Context, name string) (Thread, error) {
	row := q.queryRow(ctx, q.getThreadByNameStmt, getThreadByName, name)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listThreads = `-- name: ListThreads :many
SELECT id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
FROM threads
ORDER BY created_at
`

func (q *Queries) ListThreads(ctx context.Context) ([]Thread, error) {
	rows, err := q.query(ctx, q.listThreadsStmt, listThreads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Goal,
			&i.BaseBranch,
			&i.Branch,
			&i.WorktreePath,
			&i.SessionID,
			&i.Status,
			&i.MergePolicy,
			&i.ResultSummary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThreadSession = `-- name: UpdateThreadSession :one
UPDATE threads
SET
    session_id = ?
WHERE id = ?
RETURNING id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
`

type UpdateThreadSessionParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateThreadSession(ctx context.Context, arg UpdateThreadSessionParams) (Thread, error) {
	row := q.queryRow(ctx, q.updateThreadSessionStmt, updateThreadSession, arg.SessionID, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateThreadStatus = `-- name: UpdateThreadStatus :one
UPDATE threads
SET
    status = ?,
    error = ?,
    result_summary = ?,
    completed_at = ?
WHERE id = ?
RETURNING id, name, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at
`

type UpdateThreadStatusParams struct {
	Status        string        `json:"status"`
	Error         string        `json:"error"`
	ResultSummary string        `json:"result_summary"`
	CompletedAt   sql.NullInt64 `json:"completed_at"`
	ID            string        `json:"id"`
}

func (q *Queries) UpdateThreadStatus(ctx context.Context, arg UpdateThreadStatusParams) (Thread, error) {
	row := q.queryRow(ctx, q.updateThreadStatusStmt, updateThreadStatus,
		arg.Status,
		arg.Error,
		arg.ResultSummary,
		arg.CompletedAt,
		arg.ID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
