// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package db

import (
	"context"
	"database/sql"
)

const attributeTaskCostOnce = `-- name: AttributeTaskCostOnce :execrows
UPDATE sessions
SET cost = sessions.cost + COALESCE((SELECT child.cost FROM sessions child WHERE child.id = ?1), 0)
WHERE sessions.id = ?2
  AND EXISTS (
      SELECT 1 FROM threads
      WHERE threads.id = ?3
        AND threads.kind = 'task'
        AND threads.status = 'running'
        AND threads.session_id = ?1
        AND threads.parent_session_id = ?2
        AND threads.cost_attributed = 0
  )
`

type AttributeTaskCostOnceParams struct {
	SessionID       string `json:"session_id"`
	ParentSessionID string `json:"parent_session_id"`
	ID              string `json:"id"`
}

// Called in the same transaction as FinalizeTask. A failed transaction rolls
// this increment back, while the running/marker predicates make retries safe.
func (q *Queries) AttributeTaskCostOnce(ctx context.Context, arg AttributeTaskCostOnceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, attributeTaskCostOnce, arg.SessionID, arg.ParentSessionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
    id,
    name,
    project_path,
    goal,
    base_branch,
    branch,
    worktree_path,
    session_id,
    status,
    merge_policy,
    kind,
    parent_session_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
`

type CreateThreadParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	ProjectPath     string `json:"project_path"`
	Goal            string `json:"goal"`
	BaseBranch      string `json:"base_branch"`
	Branch          string `json:"branch"`
	WorktreePath    string `json:"worktree_path"`
	SessionID       string `json:"session_id"`
	Status          string `json:"status"`
	MergePolicy     string `json:"merge_policy"`
	Kind            string `json:"kind"`
	ParentSessionID string `json:"parent_session_id"`
}

// project_path is denormalized: once session_id is set, the project is
// also derivable through sessions.project_path. It is stored anyway
// because a thread exists (and has to be listed and looked up by name)
// before it has a session at all. The two are kept from diverging by
// construction (threadspawn.NewStore and sessionstore.NewService are both
// handed the same workspace project path) and by
// clear_thread_session_refs_on_session_delete, which drops the reference
// rather than letting it point at a deleted session's project.
func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, createThread,
		arg.ID,
		arg.Name,
		arg.ProjectPath,
		arg.Goal,
		arg.BaseBranch,
		arg.Branch,
		arg.WorktreePath,
		arg.SessionID,
		arg.Status,
		arg.MergePolicy,
		arg.Kind,
		arg.ParentSessionID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
		&i.CompletionPending,
		&i.CompletionDepth,
		&i.TerminalAt,
		&i.CostAttributed,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads
WHERE id = ?
`

func (q *Queries) DeleteThread(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteThread, id)
	return err
}

const finalizeTask = `-- name: FinalizeTask :one
UPDATE threads
SET
    status = ?1,
    error = ?2,
    result_summary = ?3,
    completed_at = ?4,
    terminal_at = ?5,
    completion_depth = ?6,
    completion_pending = 1,
    cost_attributed = 1
WHERE threads.id = ?7
  AND threads.kind = 'task'
  AND threads.status = 'running'
  AND threads.session_id = ?8
  AND threads.parent_session_id = ?9
RETURNING id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
`

type FinalizeTaskParams struct {
	Status          string        `json:"status"`
	Error           string        `json:"error"`
	ResultSummary   string        `json:"result_summary"`
	CompletedAt     sql.NullInt64 `json:"completed_at"`
	TerminalAt      sql.NullInt64 `json:"terminal_at"`
	CompletionDepth int64         `json:"completion_depth"`
	ID              string        `json:"id"`
	SessionID       string        `json:"session_id"`
	ParentSessionID string        `json:"parent_session_id"`
}

// This follows AttributeTaskCostOnce in one transaction, so terminal state,
// attribution and the durable completion outbox become visible together.
func (q *Queries) FinalizeTask(ctx context.Context, arg FinalizeTaskParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, finalizeTask,
		arg.Status,
		arg.Error,
		arg.ResultSummary,
		arg.CompletedAt,
		arg.TerminalAt,
		arg.CompletionDepth,
		arg.ID,
		arg.SessionID,
		arg.ParentSessionID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
		&i.CompletionPending,
		&i.CompletionDepth,
		&i.TerminalAt,
		&i.CostAttributed,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
FROM threads
WHERE id = ? LIMIT 1
`

// Unfiltered by kind: entries are addressed by primary key, and callers
// that hold an id already know what they asked for (id-or-name resolution,
// RunComplete matching). A kind-scoped caller uses GetThreadByName or
// ListThreads instead.
func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
		&i.CompletionPending,
		&i.CompletionDepth,
		&i.TerminalAt,
		&i.CostAttributed,
	)
	return i, err
}

const getThreadByName = `-- name: GetThreadByName :one
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
FROM threads
WHERE name = ? AND project_path = ? AND kind = 'thread' LIMIT 1
`

type GetThreadByNameParams struct {
	Name        string `json:"name"`
	ProjectPath string `json:"project_path"`
}

func (q *Queries) GetThreadByName(ctx context.Context, arg GetThreadByNameParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThreadByName, arg.Name, arg.ProjectPath)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
		&i.CompletionPending,
		&i.CompletionDepth,
		&i.TerminalAt,
		&i.CostAttributed,
	)
	return i, err
}

const listPendingTaskCompletions = `-- name: ListPendingTaskCompletions :many
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed FROM threads
WHERE project_path = ? AND kind = 'task' AND completion_pending = 1
ORDER BY terminal_at, created_at, id
`

func (q *Queries) ListPendingTaskCompletions(ctx context.Context, projectPath string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTaskCompletions, projectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectPath,
			&i.Goal,
			&i.BaseBranch,
			&i.Branch,
			&i.WorktreePath,
			&i.SessionID,
			&i.Status,
			&i.MergePolicy,
			&i.ResultSummary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Kind,
			&i.ParentSessionID,
			&i.CompletionPending,
			&i.CompletionDepth,
			&i.TerminalAt,
			&i.CostAttributed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
FROM threads
WHERE project_path = ? AND kind = 'thread'
ORDER BY created_at
`

// Thread-facing: thread_list, the dashboard, and any other caller that
// means "threads" specifically. Scoped to kind = 'thread' so a caller
// asking for threads never sees another delegation kind sharing this
// table. The generic lifecycle recovery sweep must NOT use this query;
// see ListThreadsAll.
func (q *Queries) ListThreads(ctx context.Context, projectPath string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreads, projectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectPath,
			&i.Goal,
			&i.BaseBranch,
			&i.Branch,
			&i.WorktreePath,
			&i.SessionID,
			&i.Status,
			&i.MergePolicy,
			&i.ResultSummary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Kind,
			&i.ParentSessionID,
			&i.CompletionPending,
			&i.CompletionDepth,
			&i.TerminalAt,
			&i.CostAttributed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsAll = `-- name: ListThreadsAll :many
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
FROM threads
WHERE project_path = ?
ORDER BY created_at
`

// Every delegation kind sharing this table (threads today, tasks once
// they exist), scoped to project_path but not kind. This is the listing
// the generic lifecycle recovery sweep uses: recovery must reconcile
// every kind after a restart, not just threads, or a non-thread row left
// "running" when the process died would never be caught and would sit
// displayed as active forever. Not for thread-facing callers; see
// ListThreads.
func (q *Queries) ListThreadsAll(ctx context.Context, projectPath string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreadsAll, projectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectPath,
			&i.Goal,
			&i.BaseBranch,
			&i.Branch,
			&i.WorktreePath,
			&i.SessionID,
			&i.Status,
			&i.MergePolicy,
			&i.ResultSummary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Kind,
			&i.ParentSessionID,
			&i.CompletionPending,
			&i.CompletionDepth,
			&i.TerminalAt,
			&i.CostAttributed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForGC = `-- name: ListThreadsForGC :many
SELECT id, project_path, status, updated_at, kind, worktree_path, branch
FROM threads
`

type ListThreadsForGCRow struct {
	ID           string `json:"id"`
	ProjectPath  string `json:"project_path"`
	Status       string `json:"status"`
	UpdatedAt    int64  `json:"updated_at"`
	Kind         string `json:"kind"`
	WorktreePath string `json:"worktree_path"`
	Branch       string `json:"branch"`
}

// Every delegation across every project, trimmed to the columns `sennit
// gc` needs to pick finished ones older than the retention cutoff.
// Unscoped by project_path; the caller filters by project in Go for
// --project.
//
// Deliberately unscoped by kind, unlike the display queries above. gc is
// not a thread-facing caller -- it is the only thing that reclaims rows
// here, and a task has nothing else that would: it is never merged (so
// discardMerged cannot reach it) and the task API has no removal of its
// own. Scoping this to threads meant finished tasks accumulated for the
// life of the database. A task carries no worktree, so reclaiming one is
// the row and its retention alone, with nothing left orphaned on disk.
//
// kind, worktree_path and branch are selected so gc can report the
// worktrees it strands: deleting a thread row leaves its worktree on disk
// with nothing left to find it by, so gc names them before the row goes.
func (q *Queries) ListThreadsForGC(ctx context.Context) ([]ListThreadsForGCRow, error) {
	rows, err := q.db.QueryContext(ctx, listThreadsForGC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadsForGCRow{}
	for rows.Next() {
		var i ListThreadsForGCRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectPath,
			&i.Status,
			&i.UpdatedAt,
			&i.Kind,
			&i.WorktreePath,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskCompletionDelivered = `-- name: MarkTaskCompletionDelivered :execrows
UPDATE threads
SET completion_pending = 0
WHERE id = ? AND kind = 'task' AND completion_pending = 1
`

func (q *Queries) MarkTaskCompletionDelivered(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskCompletionDelivered, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateThreadSession = `-- name: UpdateThreadSession :one
UPDATE threads
SET
    session_id = ?
WHERE id = ?
RETURNING id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
`

type UpdateThreadSessionParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateThreadSession(ctx context.Context, arg UpdateThreadSessionParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, updateThreadSession, arg.SessionID, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
		&i.CompletionPending,
		&i.CompletionDepth,
		&i.TerminalAt,
		&i.CostAttributed,
	)
	return i, err
}

const updateThreadStatus = `-- name: UpdateThreadStatus :one
UPDATE threads
SET
    status = ?,
    error = ?,
    result_summary = ?,
    completed_at = ?
WHERE id = ?
RETURNING id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id, completion_pending, completion_depth, terminal_at, cost_attributed
`

type UpdateThreadStatusParams struct {
	Status        string        `json:"status"`
	Error         string        `json:"error"`
	ResultSummary string        `json:"result_summary"`
	CompletedAt   sql.NullInt64 `json:"completed_at"`
	ID            string        `json:"id"`
}

func (q *Queries) UpdateThreadStatus(ctx context.Context, arg UpdateThreadStatusParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, updateThreadStatus,
		arg.Status,
		arg.Error,
		arg.ResultSummary,
		arg.CompletedAt,
		arg.ID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
		&i.CompletionPending,
		&i.CompletionDepth,
		&i.TerminalAt,
		&i.CostAttributed,
	)
	return i, err
}
