// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package db

import (
	"context"
	"database/sql"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (
    id,
    name,
    project_path,
    goal,
    base_branch,
    branch,
    worktree_path,
    session_id,
    status,
    merge_policy,
    kind,
    parent_session_id,
    updated_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id
`

type CreateThreadParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	ProjectPath     string `json:"project_path"`
	Goal            string `json:"goal"`
	BaseBranch      string `json:"base_branch"`
	Branch          string `json:"branch"`
	WorktreePath    string `json:"worktree_path"`
	SessionID       string `json:"session_id"`
	Status          string `json:"status"`
	MergePolicy     string `json:"merge_policy"`
	Kind            string `json:"kind"`
	ParentSessionID string `json:"parent_session_id"`
}

// project_path is denormalized: once session_id is set, the project is
// also derivable through sessions.project_path. It is stored anyway
// because a thread exists (and has to be listed and looked up by name)
// before it has a session at all. The two are kept from diverging by
// construction (threadspawn.NewStore and session.NewService are both
// handed the same workspace project path) and by
// clear_thread_session_refs_on_session_delete, which drops the reference
// rather than letting it point at a deleted session's project.
func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.queryRow(ctx, q.createThreadStmt, createThread,
		arg.ID,
		arg.Name,
		arg.ProjectPath,
		arg.Goal,
		arg.BaseBranch,
		arg.Branch,
		arg.WorktreePath,
		arg.SessionID,
		arg.Status,
		arg.MergePolicy,
		arg.Kind,
		arg.ParentSessionID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads
WHERE id = ?
`

func (q *Queries) DeleteThread(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteThreadStmt, deleteThread, id)
	return err
}

const getThread = `-- name: GetThread :one
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id
FROM threads
WHERE id = ? LIMIT 1
`

// Unfiltered by kind: entries are addressed by primary key, and callers
// that hold an id already know what they asked for (id-or-name resolution,
// RunComplete matching). A kind-scoped caller uses GetThreadByName or
// ListThreads instead.
func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.queryRow(ctx, q.getThreadStmt, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
	)
	return i, err
}

const getThreadByName = `-- name: GetThreadByName :one
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id
FROM threads
WHERE name = ? AND project_path = ? AND kind = 'thread' LIMIT 1
`

type GetThreadByNameParams struct {
	Name        string `json:"name"`
	ProjectPath string `json:"project_path"`
}

func (q *Queries) GetThreadByName(ctx context.Context, arg GetThreadByNameParams) (Thread, error) {
	row := q.queryRow(ctx, q.getThreadByNameStmt, getThreadByName, arg.Name, arg.ProjectPath)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
	)
	return i, err
}

const listThreads = `-- name: ListThreads :many
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id
FROM threads
WHERE project_path = ? AND kind = 'thread'
ORDER BY created_at
`

// Thread-facing: thread_list, the dashboard, and any other caller that
// means "threads" specifically. Scoped to kind = 'thread' so a caller
// asking for threads never sees another delegation kind sharing this
// table. The generic lifecycle recovery sweep must NOT use this query;
// see ListThreadsAll.
func (q *Queries) ListThreads(ctx context.Context, projectPath string) ([]Thread, error) {
	rows, err := q.query(ctx, q.listThreadsStmt, listThreads, projectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectPath,
			&i.Goal,
			&i.BaseBranch,
			&i.Branch,
			&i.WorktreePath,
			&i.SessionID,
			&i.Status,
			&i.MergePolicy,
			&i.ResultSummary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Kind,
			&i.ParentSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsAll = `-- name: ListThreadsAll :many
SELECT id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id
FROM threads
WHERE project_path = ?
ORDER BY created_at
`

// Every delegation kind sharing this table (threads today, tasks once
// they exist), scoped to project_path but not kind. This is the listing
// the generic lifecycle recovery sweep uses: recovery must reconcile
// every kind after a restart, not just threads, or a non-thread row left
// "running" when the process died would never be caught and would sit
// displayed as active forever. Not for thread-facing callers; see
// ListThreads.
func (q *Queries) ListThreadsAll(ctx context.Context, projectPath string) ([]Thread, error) {
	rows, err := q.query(ctx, q.listThreadsAllStmt, listThreadsAll, projectPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectPath,
			&i.Goal,
			&i.BaseBranch,
			&i.Branch,
			&i.WorktreePath,
			&i.SessionID,
			&i.Status,
			&i.MergePolicy,
			&i.ResultSummary,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.Kind,
			&i.ParentSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadsForGC = `-- name: ListThreadsForGC :many
SELECT id, project_path, status, updated_at
FROM threads
WHERE kind = 'thread'
`

type ListThreadsForGCRow struct {
	ID          string `json:"id"`
	ProjectPath string `json:"project_path"`
	Status      string `json:"status"`
	UpdatedAt   int64  `json:"updated_at"`
}

// Every thread across every project, trimmed to the columns `sennit gc`
// needs to pick finished threads older than the retention cutoff.
// Unscoped by project_path; the caller filters by project in Go for
// --project. Scoped by kind = 'thread': gc is a thread-facing caller and
// must not see other delegation kinds sharing this table.
func (q *Queries) ListThreadsForGC(ctx context.Context) ([]ListThreadsForGCRow, error) {
	rows, err := q.query(ctx, q.listThreadsForGCStmt, listThreadsForGC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadsForGCRow{}
	for rows.Next() {
		var i ListThreadsForGCRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectPath,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThreadSession = `-- name: UpdateThreadSession :one
UPDATE threads
SET
    session_id = ?
WHERE id = ?
RETURNING id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id
`

type UpdateThreadSessionParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateThreadSession(ctx context.Context, arg UpdateThreadSessionParams) (Thread, error) {
	row := q.queryRow(ctx, q.updateThreadSessionStmt, updateThreadSession, arg.SessionID, arg.ID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
	)
	return i, err
}

const updateThreadStatus = `-- name: UpdateThreadStatus :one
UPDATE threads
SET
    status = ?,
    error = ?,
    result_summary = ?,
    completed_at = ?
WHERE id = ?
RETURNING id, name, project_path, goal, base_branch, branch, worktree_path, session_id, status, merge_policy, result_summary, error, created_at, updated_at, completed_at, kind, parent_session_id
`

type UpdateThreadStatusParams struct {
	Status        string        `json:"status"`
	Error         string        `json:"error"`
	ResultSummary string        `json:"result_summary"`
	CompletedAt   sql.NullInt64 `json:"completed_at"`
	ID            string        `json:"id"`
}

func (q *Queries) UpdateThreadStatus(ctx context.Context, arg UpdateThreadStatusParams) (Thread, error) {
	row := q.queryRow(ctx, q.updateThreadStatusStmt, updateThreadStatus,
		arg.Status,
		arg.Error,
		arg.ResultSummary,
		arg.CompletedAt,
		arg.ID,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectPath,
		&i.Goal,
		&i.BaseBranch,
		&i.Branch,
		&i.WorktreePath,
		&i.SessionID,
		&i.Status,
		&i.MergePolicy,
		&i.ResultSummary,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Kind,
		&i.ParentSessionID,
	)
	return i, err
}
