// Code generated by internal/workspace/wsrpc/gen. DO NOT EDIT.

package wsrpc

import (
	"time"

	"charm.land/catwalk/pkg/catwalk"
	"github.com/rave-soft/sennit/internal/config"
	"github.com/rave-soft/sennit/internal/git"
	"github.com/rave-soft/sennit/internal/history"
	"github.com/rave-soft/sennit/internal/message"
	"github.com/rave-soft/sennit/internal/oauth"
	"github.com/rave-soft/sennit/internal/permission"
	"github.com/rave-soft/sennit/internal/proto"
	"github.com/rave-soft/sennit/internal/providers/accounts"
	"github.com/rave-soft/sennit/internal/question"
	"github.com/rave-soft/sennit/internal/session"
	"github.com/rave-soft/sennit/internal/skills"
	"github.com/rave-soft/sennit/internal/stats"
	"github.com/rave-soft/sennit/internal/wireerr"
	"github.com/rave-soft/sennit/internal/workspace"
)

// AccountCapabilitiesRequest is the request DTO for workspace.Workspace.AccountCapabilities.
type AccountCapabilitiesRequest struct {
	ProviderID string `json:"provider_id"`
}

// AccountCapabilitiesResponse is the response DTO for workspace.Workspace.AccountCapabilities.
type AccountCapabilitiesResponse struct {
	Result workspace.AccountCapabilities `json:"result"`
}

// ActivateAccountRequest is the request DTO for workspace.Workspace.ActivateAccount.
type ActivateAccountRequest struct {
	Scope      config.Scope `json:"scope"`
	ProviderID string       `json:"provider_id"`
	AccountID  string       `json:"account_id"`
}

// ActivateAccountResponse is the response DTO for workspace.Workspace.ActivateAccount.
type ActivateAccountResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// ActivateThreadRequest is the request DTO for workspace.Workspace.ActivateThread.
type ActivateThreadRequest struct {
	Id string `json:"id"`
}

// ActivateThreadResponse is the response DTO for workspace.Workspace.ActivateThread.
type ActivateThreadResponse struct {
	Result proto.Thread   `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// AgentCancelRequest is the request DTO for workspace.Workspace.AgentCancel.
type AgentCancelRequest struct {
	SessionID string `json:"session_id"`
}

// AgentCancelResponse is the response DTO for workspace.Workspace.AgentCancel.
type AgentCancelResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// AgentClearQueueRequest is the request DTO for workspace.Workspace.AgentClearQueue.
type AgentClearQueueRequest struct {
	SessionID string `json:"session_id"`
}

// AgentClearQueueResponse is the response DTO for workspace.Workspace.AgentClearQueue.
type AgentClearQueueResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// AgentIsBusyRequest is the request DTO for workspace.Workspace.AgentIsBusy.
type AgentIsBusyRequest struct{}

// AgentIsBusyResponse is the response DTO for workspace.Workspace.AgentIsBusy.
type AgentIsBusyResponse struct {
	Result bool `json:"result"`
}

// AgentIsReadyRequest is the request DTO for workspace.Workspace.AgentIsReady.
type AgentIsReadyRequest struct{}

// AgentIsReadyResponse is the response DTO for workspace.Workspace.AgentIsReady.
type AgentIsReadyResponse struct {
	Result bool `json:"result"`
}

// AgentIsSessionBusyRequest is the request DTO for workspace.Workspace.AgentIsSessionBusy.
type AgentIsSessionBusyRequest struct {
	SessionID string `json:"session_id"`
}

// AgentIsSessionBusyResponse is the response DTO for workspace.Workspace.AgentIsSessionBusy.
type AgentIsSessionBusyResponse struct {
	Result bool `json:"result"`
}

// AgentModelRequest is the request DTO for workspace.Workspace.AgentModel.
type AgentModelRequest struct{}

// AgentModelResponse is the response DTO for workspace.Workspace.AgentModel.
type AgentModelResponse struct {
	Result workspace.AgentModel `json:"result"`
}

// AgentQueuedPromptsListRequest is the request DTO for workspace.Workspace.AgentQueuedPromptsList.
type AgentQueuedPromptsListRequest struct {
	SessionID string `json:"session_id"`
}

// AgentQueuedPromptsListResponse is the response DTO for workspace.Workspace.AgentQueuedPromptsList.
type AgentQueuedPromptsListResponse struct {
	Result []string `json:"result"`
}

// AgentReadyErrRequest is the request DTO for workspace.Workspace.AgentReadyErr.
type AgentReadyErrRequest struct{}

// AgentReadyErrResponse is the response DTO for workspace.Workspace.AgentReadyErr.
type AgentReadyErrResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// AgentRunRequest is the request DTO for workspace.Workspace.AgentRun.
type AgentRunRequest struct {
	SessionID   string               `json:"session_id"`
	Prompt      string               `json:"prompt"`
	Attachments []message.Attachment `json:"attachments"`
}

// AgentRunResponse is the response DTO for workspace.Workspace.AgentRun.
type AgentRunResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// AgentSummarizeRequest is the request DTO for workspace.Workspace.AgentSummarize.
type AgentSummarizeRequest struct {
	SessionID string `json:"session_id"`
}

// AgentSummarizeResponse is the response DTO for workspace.Workspace.AgentSummarize.
type AgentSummarizeResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// ApplySessionModelRequest is the request DTO for workspace.Workspace.ApplySessionModel.
type ApplySessionModelRequest struct {
	SessionID string `json:"session_id"`
}

// ApplySessionModelResponse is the response DTO for workspace.Workspace.ApplySessionModel.
type ApplySessionModelResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// AttachProjectFileRequest is the request DTO for workspace.Workspace.AttachProjectFile.
type AttachProjectFileRequest struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

// AttachProjectFileResponse is the response DTO for workspace.Workspace.AttachProjectFile.
type AttachProjectFileResponse struct {
	Result0 message.Attachment `json:"result_0"`
	Result1 bool               `json:"result_1"`
	Err     *wireerr.Error     `json:"err,omitempty"`
}

// BackgroundJobCountsRequest is the request DTO for workspace.Workspace.BackgroundJobCounts.
type BackgroundJobCountsRequest struct{}

// BackgroundJobCountsResponse is the response DTO for workspace.Workspace.BackgroundJobCounts.
type BackgroundJobCountsResponse struct {
	Result workspace.BackgroundJobCounts `json:"result"`
}

// BuiltinSkillsRequest is the request DTO for workspace.Workspace.BuiltinSkills.
type BuiltinSkillsRequest struct{}

// BuiltinSkillsResponse is the response DTO for workspace.Workspace.BuiltinSkills.
type BuiltinSkillsResponse struct {
	Result []*skills.Skill `json:"result"`
}

// CancelTaskRequest is the request DTO for workspace.Workspace.CancelTask.
type CancelTaskRequest struct {
	Id     string `json:"id"`
	Reason string `json:"reason"`
}

// CancelTaskResponse is the response DTO for workspace.Workspace.CancelTask.
type CancelTaskResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// CancelThreadRequest is the request DTO for workspace.Workspace.CancelThread.
type CancelThreadRequest struct {
	Id     string `json:"id"`
	Reason string `json:"reason"`
}

// CancelThreadResponse is the response DTO for workspace.Workspace.CancelThread.
type CancelThreadResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// CompleteOAuthRequest is the request DTO for workspace.Workspace.CompleteOAuth.
type CompleteOAuthRequest struct {
	ProviderID      string       `json:"provider_id"`
	ProxyURL        string       `json:"proxy_url"`
	Token           *oauth.Token `json:"token"`
	ForceNewAccount bool         `json:"force_new_account"`
}

// CompleteOAuthResponse is the response DTO for workspace.Workspace.CompleteOAuth.
type CompleteOAuthResponse struct {
	Result workspace.OAuthCompletion `json:"result"`
	Err    *wireerr.Error            `json:"err,omitempty"`
}

// ConfigRequest is the request DTO for workspace.Workspace.Config.
type ConfigRequest struct{}

// ConfigResponse is the response DTO for workspace.Workspace.Config.
type ConfigResponse struct {
	Result *workspace.FrontendConfig `json:"result"`
}

// ConfigProblemsRequest is the request DTO for workspace.Workspace.ConfigProblems.
type ConfigProblemsRequest struct{}

// ConfigProblemsResponse is the response DTO for workspace.Workspace.ConfigProblems.
type ConfigProblemsResponse struct {
	Result []config.Problem `json:"result"`
}

// ConfigureCustomProviderRequest is the request DTO for workspace.Workspace.ConfigureCustomProvider.
type ConfigureCustomProviderRequest struct {
	Scope  config.Scope                            `json:"scope"`
	Params workspace.ConfigureCustomProviderParams `json:"params"`
}

// ConfigureCustomProviderResponse is the response DTO for workspace.Workspace.ConfigureCustomProvider.
type ConfigureCustomProviderResponse struct {
	Result []catwalk.Model `json:"result"`
	Err    *wireerr.Error  `json:"err,omitempty"`
}

// CreateSessionRequest is the request DTO for workspace.Workspace.CreateSession.
type CreateSessionRequest struct {
	Title string `json:"title"`
}

// CreateSessionResponse is the response DTO for workspace.Workspace.CreateSession.
type CreateSessionResponse struct {
	Result session.Session `json:"result"`
	Err    *wireerr.Error  `json:"err,omitempty"`
}

// CreateThreadRequest is the request DTO for workspace.Workspace.CreateThread.
type CreateThreadRequest struct {
	Req proto.CreateThreadRequest `json:"req"`
}

// CreateThreadResponse is the response DTO for workspace.Workspace.CreateThread.
type CreateThreadResponse struct {
	Result proto.Thread   `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// CurrentPlanUsageRequest is the request DTO for workspace.Workspace.CurrentPlanUsage.
type CurrentPlanUsageRequest struct {
	ProviderID string `json:"provider_id"`
}

// CurrentPlanUsageResponse is the response DTO for workspace.Workspace.CurrentPlanUsage.
type CurrentPlanUsageResponse struct {
	Result0 accounts.Usage `json:"result_0"`
	Result1 bool           `json:"result_1"`
}

// CustomProviderTypesRequest is the request DTO for workspace.Workspace.CustomProviderTypes.
type CustomProviderTypesRequest struct{}

// CustomProviderTypesResponse is the response DTO for workspace.Workspace.CustomProviderTypes.
type CustomProviderTypesResponse struct {
	Result []string `json:"result"`
}

// DeleteSessionRequest is the request DTO for workspace.Workspace.DeleteSession.
type DeleteSessionRequest struct {
	SessionID string `json:"session_id"`
}

// DeleteSessionResponse is the response DTO for workspace.Workspace.DeleteSession.
type DeleteSessionResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// DisableDockerMCPRequest is the request DTO for workspace.Workspace.DisableDockerMCP.
type DisableDockerMCPRequest struct{}

// DisableDockerMCPResponse is the response DTO for workspace.Workspace.DisableDockerMCP.
type DisableDockerMCPResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// DockerMCPAvailableRequest is the request DTO for workspace.Workspace.DockerMCPAvailable.
type DockerMCPAvailableRequest struct{}

// DockerMCPAvailableResponse is the response DTO for workspace.Workspace.DockerMCPAvailable.
type DockerMCPAvailableResponse struct {
	Available bool `json:"available"`
	Known     bool `json:"known"`
}

// DoctorProblemsRequest is the request DTO for workspace.Workspace.DoctorProblems.
type DoctorProblemsRequest struct{}

// DoctorProblemsResponse is the response DTO for workspace.Workspace.DoctorProblems.
type DoctorProblemsResponse struct {
	Result []config.Problem `json:"result"`
}

// EnableDockerMCPRequest is the request DTO for workspace.Workspace.EnableDockerMCP.
type EnableDockerMCPRequest struct{}

// EnableDockerMCPResponse is the response DTO for workspace.Workspace.EnableDockerMCP.
type EnableDockerMCPResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// FileTrackerLastReadTimeRequest is the request DTO for workspace.Workspace.FileTrackerLastReadTime.
type FileTrackerLastReadTimeRequest struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

// FileTrackerLastReadTimeResponse is the response DTO for workspace.Workspace.FileTrackerLastReadTime.
type FileTrackerLastReadTimeResponse struct {
	Result time.Time      `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// FileTrackerListReadFilesRequest is the request DTO for workspace.Workspace.FileTrackerListReadFiles.
type FileTrackerListReadFilesRequest struct {
	SessionID string `json:"session_id"`
}

// FileTrackerListReadFilesResponse is the response DTO for workspace.Workspace.FileTrackerListReadFiles.
type FileTrackerListReadFilesResponse struct {
	Result []string       `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// FileTrackerRecordReadRequest is the request DTO for workspace.Workspace.FileTrackerRecordRead.
type FileTrackerRecordReadRequest struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

// FileTrackerRecordReadResponse is the response DTO for workspace.Workspace.FileTrackerRecordRead.
type FileTrackerRecordReadResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// GetLastSessionRequest is the request DTO for workspace.Workspace.GetLastSession.
type GetLastSessionRequest struct{}

// GetLastSessionResponse is the response DTO for workspace.Workspace.GetLastSession.
type GetLastSessionResponse struct {
	Result session.Session `json:"result"`
	Err    *wireerr.Error  `json:"err,omitempty"`
}

// GetMCPPromptRequest is the request DTO for workspace.Workspace.GetMCPPrompt.
type GetMCPPromptRequest struct {
	ClientID string            `json:"client_id"`
	PromptID string            `json:"prompt_id"`
	Args     map[string]string `json:"args"`
}

// GetMCPPromptResponse is the response DTO for workspace.Workspace.GetMCPPrompt.
type GetMCPPromptResponse struct {
	Result string         `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// GetSessionRequest is the request DTO for workspace.Workspace.GetSession.
type GetSessionRequest struct {
	SessionID string `json:"session_id"`
}

// GetSessionResponse is the response DTO for workspace.Workspace.GetSession.
type GetSessionResponse struct {
	Result session.Session `json:"result"`
	Err    *wireerr.Error  `json:"err,omitempty"`
}

// ImportCopilotRequest is the request DTO for workspace.Workspace.ImportCopilot.
type ImportCopilotRequest struct{}

// ImportCopilotResponse is the response DTO for workspace.Workspace.ImportCopilot.
type ImportCopilotResponse struct {
	Result0 *oauth.Token   `json:"result_0"`
	Result1 bool           `json:"result_1"`
	Err     *wireerr.Error `json:"err,omitempty"`
}

// InitCoderAgentRequest is the request DTO for workspace.Workspace.InitCoderAgent.
type InitCoderAgentRequest struct{}

// InitCoderAgentResponse is the response DTO for workspace.Workspace.InitCoderAgent.
type InitCoderAgentResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// InitCoderAgentNonInteractiveRequest is the request DTO for workspace.Workspace.InitCoderAgentNonInteractive.
type InitCoderAgentNonInteractiveRequest struct{}

// InitCoderAgentNonInteractiveResponse is the response DTO for workspace.Workspace.InitCoderAgentNonInteractive.
type InitCoderAgentNonInteractiveResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// InitializePromptRequest is the request DTO for workspace.Workspace.InitializePrompt.
type InitializePromptRequest struct{}

// InitializePromptResponse is the response DTO for workspace.Workspace.InitializePrompt.
type InitializePromptResponse struct {
	Result string         `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// KnownProvidersRequest is the request DTO for workspace.Workspace.KnownProviders.
type KnownProvidersRequest struct{}

// KnownProvidersResponse is the response DTO for workspace.Workspace.KnownProviders.
type KnownProvidersResponse struct {
	Result []catwalk.Provider `json:"result"`
}

// LSPGetDiagnosticCountsRequest is the request DTO for workspace.Workspace.LSPGetDiagnosticCounts.
type LSPGetDiagnosticCountsRequest struct {
	Name string `json:"name"`
}

// LSPGetDiagnosticCountsResponse is the response DTO for workspace.Workspace.LSPGetDiagnosticCounts.
type LSPGetDiagnosticCountsResponse struct {
	Result proto.LSPDiagnosticCounts `json:"result"`
}

// LSPGetStatesRequest is the request DTO for workspace.Workspace.LSPGetStates.
type LSPGetStatesRequest struct{}

// LSPGetStatesResponse is the response DTO for workspace.Workspace.LSPGetStates.
type LSPGetStatesResponse struct {
	Result map[string]workspace.LSPClientInfo `json:"result"`
}

// LSPStartRequest is the request DTO for workspace.Workspace.LSPStart.
type LSPStartRequest struct {
	Path string `json:"path"`
}

// LSPStartResponse is the response DTO for workspace.Workspace.LSPStart.
type LSPStartResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// LSPStopAllRequest is the request DTO for workspace.Workspace.LSPStopAll.
type LSPStopAllRequest struct{}

// LSPStopAllResponse is the response DTO for workspace.Workspace.LSPStopAll.
type LSPStopAllResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// ListAccountsRequest is the request DTO for workspace.Workspace.ListAccounts.
type ListAccountsRequest struct {
	ProviderID string `json:"provider_id"`
}

// ListAccountsResponse is the response DTO for workspace.Workspace.ListAccounts.
type ListAccountsResponse struct {
	Result []workspace.FrontendAccount `json:"result"`
	Err    *wireerr.Error              `json:"err,omitempty"`
}

// ListAllUserMessagesRequest is the request DTO for workspace.Workspace.ListAllUserMessages.
type ListAllUserMessagesRequest struct{}

// ListAllUserMessagesResponse is the response DTO for workspace.Workspace.ListAllUserMessages.
type ListAllUserMessagesResponse struct {
	Result []message.Message `json:"result"`
	Err    *wireerr.Error    `json:"err,omitempty"`
}

// ListCustomCommandsRequest is the request DTO for workspace.Workspace.ListCustomCommands.
type ListCustomCommandsRequest struct{}

// ListCustomCommandsResponse is the response DTO for workspace.Workspace.ListCustomCommands.
type ListCustomCommandsResponse struct {
	Result []workspace.CustomCommand `json:"result"`
	Err    *wireerr.Error            `json:"err,omitempty"`
}

// ListMCPPromptsRequest is the request DTO for workspace.Workspace.ListMCPPrompts.
type ListMCPPromptsRequest struct{}

// ListMCPPromptsResponse is the response DTO for workspace.Workspace.ListMCPPrompts.
type ListMCPPromptsResponse struct {
	Result []workspace.MCPPrompt `json:"result"`
	Err    *wireerr.Error        `json:"err,omitempty"`
}

// ListMessagesRequest is the request DTO for workspace.Workspace.ListMessages.
type ListMessagesRequest struct {
	SessionID string `json:"session_id"`
}

// ListMessagesResponse is the response DTO for workspace.Workspace.ListMessages.
type ListMessagesResponse struct {
	Result []message.Message `json:"result"`
	Err    *wireerr.Error    `json:"err,omitempty"`
}

// ListMessagesBySessionIDsRequest is the request DTO for workspace.Workspace.ListMessagesBySessionIDs.
type ListMessagesBySessionIDsRequest struct {
	RootSessionID string   `json:"root_session_id"`
	Generation    uint64   `json:"generation"`
	SessionIDs    []string `json:"session_i_ds"`
}

// ListMessagesBySessionIDsResponse is the response DTO for workspace.Workspace.ListMessagesBySessionIDs.
type ListMessagesBySessionIDsResponse struct {
	Result map[string][]message.Message `json:"result"`
	Err    *wireerr.Error               `json:"err,omitempty"`
}

// ListProjectFilesRequest is the request DTO for workspace.Workspace.ListProjectFiles.
type ListProjectFilesRequest struct {
	Depth int `json:"depth"`
	Limit int `json:"limit"`
}

// ListProjectFilesResponse is the response DTO for workspace.Workspace.ListProjectFiles.
type ListProjectFilesResponse struct {
	Result []string       `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// ListSessionHistoryRequest is the request DTO for workspace.Workspace.ListSessionHistory.
type ListSessionHistoryRequest struct {
	SessionID string `json:"session_id"`
}

// ListSessionHistoryResponse is the response DTO for workspace.Workspace.ListSessionHistory.
type ListSessionHistoryResponse struct {
	Result []history.File `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// ListSessionsRequest is the request DTO for workspace.Workspace.ListSessions.
type ListSessionsRequest struct{}

// ListSessionsResponse is the response DTO for workspace.Workspace.ListSessions.
type ListSessionsResponse struct {
	Result []session.Session `json:"result"`
	Err    *wireerr.Error    `json:"err,omitempty"`
}

// ListSkillsRequest is the request DTO for workspace.Workspace.ListSkills.
type ListSkillsRequest struct{}

// ListSkillsResponse is the response DTO for workspace.Workspace.ListSkills.
type ListSkillsResponse struct {
	Result []skills.CatalogEntry `json:"result"`
	Err    *wireerr.Error        `json:"err,omitempty"`
}

// ListTasksRequest is the request DTO for workspace.Workspace.ListTasks.
type ListTasksRequest struct{}

// ListTasksResponse is the response DTO for workspace.Workspace.ListTasks.
type ListTasksResponse struct {
	Result []proto.Thread `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// ListThreadsRequest is the request DTO for workspace.Workspace.ListThreads.
type ListThreadsRequest struct{}

// ListThreadsResponse is the response DTO for workspace.Workspace.ListThreads.
type ListThreadsResponse struct {
	Result []proto.Thread `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// ListUserMessagesRequest is the request DTO for workspace.Workspace.ListUserMessages.
type ListUserMessagesRequest struct {
	SessionID string `json:"session_id"`
}

// ListUserMessagesResponse is the response DTO for workspace.Workspace.ListUserMessages.
type ListUserMessagesResponse struct {
	Result []message.Message `json:"result"`
	Err    *wireerr.Error    `json:"err,omitempty"`
}

// MCPAuthURLRequest is the request DTO for workspace.Workspace.MCPAuthURL.
type MCPAuthURLRequest struct {
	Name string `json:"name"`
}

// MCPAuthURLResponse is the response DTO for workspace.Workspace.MCPAuthURL.
type MCPAuthURLResponse struct {
	Result string `json:"result"`
}

// MCPAuthenticateRequest is the request DTO for workspace.Workspace.MCPAuthenticate.
type MCPAuthenticateRequest struct {
	Name string `json:"name"`
}

// MCPAuthenticateResponse is the response DTO for workspace.Workspace.MCPAuthenticate.
type MCPAuthenticateResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// MCPGetStatesRequest is the request DTO for workspace.Workspace.MCPGetStates.
type MCPGetStatesRequest struct{}

// MCPGetStatesResponse is the response DTO for workspace.Workspace.MCPGetStates.
type MCPGetStatesResponse struct {
	Result map[string]workspace.MCPClientInfo `json:"result"`
}

// MCPPendingAuthRequest is the request DTO for workspace.Workspace.MCPPendingAuth.
type MCPPendingAuthRequest struct{}

// MCPPendingAuthResponse is the response DTO for workspace.Workspace.MCPPendingAuth.
type MCPPendingAuthResponse struct {
	Result []workspace.MCPPendingAuthServer `json:"result"`
}

// MCPRefreshPromptsRequest is the request DTO for workspace.Workspace.MCPRefreshPrompts.
type MCPRefreshPromptsRequest struct {
	Name string `json:"name"`
}

// MCPRefreshPromptsResponse is the response DTO for workspace.Workspace.MCPRefreshPrompts.
type MCPRefreshPromptsResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// MCPRefreshResourcesRequest is the request DTO for workspace.Workspace.MCPRefreshResources.
type MCPRefreshResourcesRequest struct {
	Name string `json:"name"`
}

// MCPRefreshResourcesResponse is the response DTO for workspace.Workspace.MCPRefreshResources.
type MCPRefreshResourcesResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// MCPResourcesRequest is the request DTO for workspace.Workspace.MCPResources.
type MCPResourcesRequest struct{}

// MCPResourcesResponse is the response DTO for workspace.Workspace.MCPResources.
type MCPResourcesResponse struct {
	Result []workspace.MCPResourceInfo `json:"result"`
}

// MarkProjectInitializedRequest is the request DTO for workspace.Workspace.MarkProjectInitialized.
type MarkProjectInitializedRequest struct{}

// MarkProjectInitializedResponse is the response DTO for workspace.Workspace.MarkProjectInitialized.
type MarkProjectInitializedResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// OAuthConfiguredProxyRequest is the request DTO for workspace.Workspace.OAuthConfiguredProxy.
type OAuthConfiguredProxyRequest struct {
	ProviderID string `json:"provider_id"`
}

// OAuthConfiguredProxyResponse is the response DTO for workspace.Workspace.OAuthConfiguredProxy.
type OAuthConfiguredProxyResponse struct {
	Result string `json:"result"`
}

// OAuthValidateProxyRequest is the request DTO for workspace.Workspace.OAuthValidateProxy.
type OAuthValidateProxyRequest struct {
	ProviderID string `json:"provider_id"`
	ProxyURL   string `json:"proxy_url"`
}

// OAuthValidateProxyResponse is the response DTO for workspace.Workspace.OAuthValidateProxy.
type OAuthValidateProxyResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// OverridePreferredModelRequest is the request DTO for workspace.Workspace.OverridePreferredModel.
type OverridePreferredModelRequest struct {
	Model config.SelectedModel `json:"model"`
}

// OverridePreferredModelResponse is the response DTO for workspace.Workspace.OverridePreferredModel.
type OverridePreferredModelResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// PermissionDenyRequest is the request DTO for workspace.Workspace.PermissionDeny.
type PermissionDenyRequest struct {
	Perm permission.PermissionRequest `json:"perm"`
}

// PermissionDenyResponse is the response DTO for workspace.Workspace.PermissionDeny.
type PermissionDenyResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// PermissionGrantRequest is the request DTO for workspace.Workspace.PermissionGrant.
type PermissionGrantRequest struct {
	Perm permission.PermissionRequest `json:"perm"`
}

// PermissionGrantResponse is the response DTO for workspace.Workspace.PermissionGrant.
type PermissionGrantResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// PermissionGrantPersistentRequest is the request DTO for workspace.Workspace.PermissionGrantPersistent.
type PermissionGrantPersistentRequest struct {
	Perm permission.PermissionRequest `json:"perm"`
}

// PermissionGrantPersistentResponse is the response DTO for workspace.Workspace.PermissionGrantPersistent.
type PermissionGrantPersistentResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// PermissionSetSkipRequestsRequest is the request DTO for workspace.Workspace.PermissionSetSkipRequests.
type PermissionSetSkipRequestsRequest struct {
	Skip bool `json:"skip"`
}

// PermissionSetSkipRequestsResponse is the response DTO for workspace.Workspace.PermissionSetSkipRequests.
type PermissionSetSkipRequestsResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// PermissionSkipRequestsRequest is the request DTO for workspace.Workspace.PermissionSkipRequests.
type PermissionSkipRequestsRequest struct{}

// PermissionSkipRequestsResponse is the response DTO for workspace.Workspace.PermissionSkipRequests.
type PermissionSkipRequestsResponse struct {
	Result bool `json:"result"`
}

// PrepareSessionChangesRequest is the request DTO for workspace.Workspace.PrepareSessionChanges.
type PrepareSessionChangesRequest struct {
	SessionID string `json:"session_id"`
}

// PrepareSessionChangesResponse is the response DTO for workspace.Workspace.PrepareSessionChanges.
type PrepareSessionChangesResponse struct {
	Result []workspace.SessionFile `json:"result"`
	Err    *wireerr.Error          `json:"err,omitempty"`
}

// ProjectNeedsInitializationRequest is the request DTO for workspace.Workspace.ProjectNeedsInitialization.
type ProjectNeedsInitializationRequest struct{}

// ProjectNeedsInitializationResponse is the response DTO for workspace.Workspace.ProjectNeedsInitialization.
type ProjectNeedsInitializationResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// PurgeAccountsRequest is the request DTO for workspace.Workspace.PurgeAccounts.
type PurgeAccountsRequest struct {
	Scope      config.Scope `json:"scope"`
	ProviderID string       `json:"provider_id"`
}

// PurgeAccountsResponse is the response DTO for workspace.Workspace.PurgeAccounts.
type PurgeAccountsResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// QuestionAnswerRequest is the request DTO for workspace.Workspace.QuestionAnswer.
type QuestionAnswerRequest struct {
	BatchID   string            `json:"batch_id"`
	Responses []question.Answer `json:"responses"`
}

// QuestionAnswerResponse is the response DTO for workspace.Workspace.QuestionAnswer.
type QuestionAnswerResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// QuestionCancelRequest is the request DTO for workspace.Workspace.QuestionCancel.
type QuestionCancelRequest struct {
	BatchID string `json:"batch_id"`
}

// QuestionCancelResponse is the response DTO for workspace.Workspace.QuestionCancel.
type QuestionCancelResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// ReadMCPResourceRequest is the request DTO for workspace.Workspace.ReadMCPResource.
type ReadMCPResourceRequest struct {
	Name string `json:"name"`
	Uri  string `json:"uri"`
}

// ReadMCPResourceResponse is the response DTO for workspace.Workspace.ReadMCPResource.
type ReadMCPResourceResponse struct {
	Result []workspace.MCPResourceContents `json:"result"`
	Err    *wireerr.Error                  `json:"err,omitempty"`
}

// ReadSkillRequest is the request DTO for workspace.Workspace.ReadSkill.
type ReadSkillRequest struct {
	SkillID string `json:"skill_id"`
}

// ReadSkillResponse is the response DTO for workspace.Workspace.ReadSkill.
type ReadSkillResponse struct {
	Result0 []byte                 `json:"result_0"`
	Result1 skills.SkillReadResult `json:"result_1"`
	Err     *wireerr.Error         `json:"err,omitempty"`
}

// RecordAccountRequest is the request DTO for workspace.Workspace.RecordAccount.
type RecordAccountRequest struct {
	Scope      config.Scope              `json:"scope"`
	ProviderID string                    `json:"provider_id"`
	Cred       accounts.LegacyCredential `json:"cred"`
}

// RecordAccountResponse is the response DTO for workspace.Workspace.RecordAccount.
type RecordAccountResponse struct {
	Result workspace.FrontendAccount `json:"result"`
	Err    *wireerr.Error            `json:"err,omitempty"`
}

// RefreshAccountLimitsRequest is the request DTO for workspace.Workspace.RefreshAccountLimits.
type RefreshAccountLimitsRequest struct {
	ProviderID string `json:"provider_id"`
}

// RefreshAccountLimitsResponse is the response DTO for workspace.Workspace.RefreshAccountLimits.
type RefreshAccountLimitsResponse struct {
	Result []workspace.FrontendAccount `json:"result"`
	Err    *wireerr.Error              `json:"err,omitempty"`
}

// RefreshDockerMCPAvailabilityRequest is the request DTO for workspace.Workspace.RefreshDockerMCPAvailability.
type RefreshDockerMCPAvailabilityRequest struct{}

// RefreshDockerMCPAvailabilityResponse is the response DTO for workspace.Workspace.RefreshDockerMCPAvailability.
type RefreshDockerMCPAvailabilityResponse struct {
	Result bool           `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// RefreshMCPToolsRequest is the request DTO for workspace.Workspace.RefreshMCPTools.
type RefreshMCPToolsRequest struct {
	Name string `json:"name"`
}

// RefreshMCPToolsResponse is the response DTO for workspace.Workspace.RefreshMCPTools.
type RefreshMCPToolsResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// RefreshOAuthTokenRequest is the request DTO for workspace.Workspace.RefreshOAuthToken.
type RefreshOAuthTokenRequest struct {
	Scope      config.Scope `json:"scope"`
	ProviderID string       `json:"provider_id"`
}

// RefreshOAuthTokenResponse is the response DTO for workspace.Workspace.RefreshOAuthToken.
type RefreshOAuthTokenResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// RefreshOAuthTokenForAccountRequest is the request DTO for workspace.Workspace.RefreshOAuthTokenForAccount.
type RefreshOAuthTokenForAccountRequest struct {
	Scope      config.Scope `json:"scope"`
	ProviderID string       `json:"provider_id"`
	AccountID  string       `json:"account_id"`
}

// RefreshOAuthTokenForAccountResponse is the response DTO for workspace.Workspace.RefreshOAuthTokenForAccount.
type RefreshOAuthTokenForAccountResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// RefreshProviderModelsRequest is the request DTO for workspace.Workspace.RefreshProviderModels.
type RefreshProviderModelsRequest struct {
	ProviderID string `json:"provider_id"`
}

// RefreshProviderModelsResponse is the response DTO for workspace.Workspace.RefreshProviderModels.
type RefreshProviderModelsResponse struct {
	Result []workspace.ModelRefreshResult `json:"result"`
	Err    *wireerr.Error                 `json:"err,omitempty"`
}

// RemoveAccountRequest is the request DTO for workspace.Workspace.RemoveAccount.
type RemoveAccountRequest struct {
	Scope      config.Scope `json:"scope"`
	ProviderID string       `json:"provider_id"`
	AccountID  string       `json:"account_id"`
}

// RemoveAccountResponse is the response DTO for workspace.Workspace.RemoveAccount.
type RemoveAccountResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// RemoveConfigFieldRequest is the request DTO for workspace.Workspace.RemoveConfigField.
type RemoveConfigFieldRequest struct {
	Scope config.Scope `json:"scope"`
	Key   string       `json:"key"`
}

// RemoveConfigFieldResponse is the response DTO for workspace.Workspace.RemoveConfigField.
type RemoveConfigFieldResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// RemoveThreadRequest is the request DTO for workspace.Workspace.RemoveThread.
type RemoveThreadRequest struct {
	Id   string                    `json:"id"`
	Opts proto.RemoveThreadOptions `json:"opts"`
}

// RemoveThreadResponse is the response DTO for workspace.Workspace.RemoveThread.
type RemoveThreadResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// RenameSessionRequest is the request DTO for workspace.Workspace.RenameSession.
type RenameSessionRequest struct {
	SessionID string `json:"session_id"`
	Title     string `json:"title"`
}

// RenameSessionResponse is the response DTO for workspace.Workspace.RenameSession.
type RenameSessionResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// SessionDescendantCostRequest is the request DTO for workspace.Workspace.SessionDescendantCost.
type SessionDescendantCostRequest struct {
	SessionID string `json:"session_id"`
}

// SessionDescendantCostResponse is the response DTO for workspace.Workspace.SessionDescendantCost.
type SessionDescendantCostResponse struct {
	Result float64        `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// SetConfigFieldRequest is the request DTO for workspace.Workspace.SetConfigField.
type SetConfigFieldRequest struct {
	Scope config.Scope `json:"scope"`
	Key   string       `json:"key"`
	Value any          `json:"value"`
}

// SetConfigFieldResponse is the response DTO for workspace.Workspace.SetConfigField.
type SetConfigFieldResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// SetCurrentSessionRequest is the request DTO for workspace.Workspace.SetCurrentSession.
type SetCurrentSessionRequest struct {
	SessionID string `json:"session_id"`
}

// SetCurrentSessionResponse is the response DTO for workspace.Workspace.SetCurrentSession.
type SetCurrentSessionResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// SetCurrentSessionGenerationRequest is the request DTO for workspace.Workspace.SetCurrentSessionGeneration.
type SetCurrentSessionGenerationRequest struct {
	SessionID  string `json:"session_id"`
	Generation uint64 `json:"generation"`
}

// SetCurrentSessionGenerationResponse is the response DTO for workspace.Workspace.SetCurrentSessionGeneration.
type SetCurrentSessionGenerationResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// SetProviderAPIKeyRequest is the request DTO for workspace.Workspace.SetProviderAPIKey.
type SetProviderAPIKeyRequest struct {
	Scope      config.Scope `json:"scope"`
	ProviderID string       `json:"provider_id"`
	ApiKey     string       `json:"api_key"`
}

// SetProviderAPIKeyResponse is the response DTO for workspace.Workspace.SetProviderAPIKey.
type SetProviderAPIKeyResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// SetProviderProxyRequest is the request DTO for workspace.Workspace.SetProviderProxy.
type SetProviderProxyRequest struct {
	ProviderID string `json:"provider_id"`
	Proxy      string `json:"proxy"`
}

// SetProviderProxyResponse is the response DTO for workspace.Workspace.SetProviderProxy.
type SetProviderProxyResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// SkillStatesRequest is the request DTO for workspace.Workspace.SkillStates.
type SkillStatesRequest struct{}

// SkillStatesResponse is the response DTO for workspace.Workspace.SkillStates.
type SkillStatesResponse struct {
	Result []*skills.SkillState `json:"result"`
}

// StatsRequest is the request DTO for workspace.Workspace.Stats.
type StatsRequest struct {
	Req stats.Request `json:"req"`
}

// StatsResponse is the response DTO for workspace.Workspace.Stats.
type StatsResponse struct {
	Result stats.Snapshot `json:"result"`
	Err    *wireerr.Error `json:"err,omitempty"`
}

// SupportsTasksRequest is the request DTO for workspace.Workspace.SupportsTasks.
type SupportsTasksRequest struct{}

// SupportsTasksResponse is the response DTO for workspace.Workspace.SupportsTasks.
type SupportsTasksResponse struct {
	Result bool `json:"result"`
}

// SupportsThreadsRequest is the request DTO for workspace.Workspace.SupportsThreads.
type SupportsThreadsRequest struct{}

// SupportsThreadsResponse is the response DTO for workspace.Workspace.SupportsThreads.
type SupportsThreadsResponse struct {
	Result bool `json:"result"`
}

// UncommittedFilesRequest is the request DTO for workspace.Workspace.UncommittedFiles.
type UncommittedFilesRequest struct{}

// UncommittedFilesResponse is the response DTO for workspace.Workspace.UncommittedFiles.
type UncommittedFilesResponse struct {
	Result []git.FileChange `json:"result"`
	Err    *wireerr.Error   `json:"err,omitempty"`
}

// UpdateAccountFieldsRequest is the request DTO for workspace.Workspace.UpdateAccountFields.
type UpdateAccountFieldsRequest struct {
	ProviderID string                `json:"provider_id"`
	AccountID  string                `json:"account_id"`
	Edit       workspace.AccountEdit `json:"edit"`
}

// UpdateAccountFieldsResponse is the response DTO for workspace.Workspace.UpdateAccountFields.
type UpdateAccountFieldsResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// UpdateAgentModelRequest is the request DTO for workspace.Workspace.UpdateAgentModel.
type UpdateAgentModelRequest struct{}

// UpdateAgentModelResponse is the response DTO for workspace.Workspace.UpdateAgentModel.
type UpdateAgentModelResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// UpdatePreferredModelRequest is the request DTO for workspace.Workspace.UpdatePreferredModel.
type UpdatePreferredModelRequest struct {
	Scope config.Scope         `json:"scope"`
	Model config.SelectedModel `json:"model"`
}

// UpdatePreferredModelResponse is the response DTO for workspace.Workspace.UpdatePreferredModel.
type UpdatePreferredModelResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// VerifyProviderAPIKeyRequest is the request DTO for workspace.Workspace.VerifyProviderAPIKey.
type VerifyProviderAPIKeyRequest struct {
	ProviderID string `json:"provider_id"`
	ApiKey     string `json:"api_key"`
}

// VerifyProviderAPIKeyResponse is the response DTO for workspace.Workspace.VerifyProviderAPIKey.
type VerifyProviderAPIKeyResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// WaitForMCPInitRequest is the request DTO for workspace.Workspace.WaitForMCPInit.
type WaitForMCPInitRequest struct{}

// WaitForMCPInitResponse is the response DTO for workspace.Workspace.WaitForMCPInit.
type WaitForMCPInitResponse struct {
	Err *wireerr.Error `json:"err,omitempty"`
}

// WorkingDirRequest is the request DTO for workspace.Workspace.WorkingDir.
type WorkingDirRequest struct{}

// WorkingDirResponse is the response DTO for workspace.Workspace.WorkingDir.
type WorkingDirResponse struct {
	Result string `json:"result"`
}

// WorktreeStateRequest is the request DTO for workspace.Workspace.WorktreeState.
type WorktreeStateRequest struct{}

// WorktreeStateResponse is the response DTO for workspace.Workspace.WorktreeState.
type WorktreeStateResponse struct {
	Result workspace.WorktreeState `json:"result"`
}
